// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { SYNC_OPERATION_REGISTRATIONS as carvitals_v01 } from "./carVitals/v01/generated-sync-operation-registry.ts";
import { SYNC_OPERATION_REGISTRATIONS as creditcheck_v01 } from "./creditCheck/v01/generated-sync-operation-registry.ts";
import { SYNC_OPERATION_REGISTRATIONS as creditcheck_v02 } from "./creditCheck/v02/generated-sync-operation-registry.ts";
import { SYNC_OPERATION_REGISTRATIONS as taskmachineconfig_v01 } from "./taskMachineConfig/v01/generated-sync-operation-registry.ts";
import { SYNC_OPERATION_REGISTRATIONS as taskmachineconfig_v02 } from "./taskMachineConfig/v02/generated-sync-operation-registry.ts";
import { SYNC_OPERATION_REGISTRATIONS as vitalsworkflow_v01 } from "./vitalsWorkflow/v01/generated-sync-operation-registry.ts";
import { SYNC_OPERATION_REGISTRATIONS as vitalsworkflow_v02 } from "./vitalsWorkflow/v02/generated-sync-operation-registry.ts";

export const SYNC_OPERATION_REGISTRATIONS = [
  ...carvitals_v01,
  ...creditcheck_v01,
  ...creditcheck_v02,
  ...taskmachineconfig_v01,
  ...taskmachineconfig_v02,
  ...vitalsworkflow_v01,
  ...vitalsworkflow_v02,
];
