// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
// TypeScript worker SDK: connects to the gateway's sidecar Unix socket via
// the generated pgfsm.sidecargateway.v1.SidecarGatewayService bidi-streaming
// client (@pgfsm/proto-codegen, a Deno workspace-linked package — see #103 —
// from packages/fsm-proto-codegen/proto/fsm-core-async-op-worker/pgfsm/sidecargateway/v1/sidecar_gateway.proto,
// #100), registers
// actors from a compiler-generated registry, and serves invoke requests.
//
// Actor discovery is no longer a runtime folder scan + dynamic `import()` —
// `fsm-compiler-ts` generates a static, self-describing registry
// (`ActorRegistration[]`, see `packages/fsm-compiler-ts/src/operation-logic-scaffold.ts`'s
// `writeActorsRegistry`/`writeAggregateActorsRegistry`) that this SDK just
// iterates. `ActorWorker` takes that array directly; the CLI is what wires it
// to a fixed, statically-imported registry file (see cli.ts) — this module
// stays registry-source-agnostic so it's easy to test with a synthetic array.
//
// This is the reference implementation for a compiled-language worker SDK
// (e.g. Rust) to follow — see ADR-003's Activity Gateway revision.

import { getLogger } from "@logtape/logtape";
import { createClient } from "@connectrpc/connect";
import {
  createGrpcTransport,
  Http2SessionManager,
} from "@connectrpc/connect-node";
import * as net from "node:net";
import { SidecarGatewayService } from "@pgfsm/proto-codegen/sidecargateway/v1/connect";
import {
  Heartbeat,
  type Invoke,
  InvokeError,
  InvokeErrorDetail,
  InvokeResult,
  Register,
  SessionRequest,
  type SessionResponse,
  Unregister,
} from "@pgfsm/proto-codegen/sidecargateway/v1/pb";

const logger = getLogger([
  "@pgfsm/worker",
  "async-op-worker-gateway",
  "worker-sdk-ts",
]);

// `deno check` fails to merge these generated classes' sibling .d.ts type
// declarations with their .js value bindings when a class name is used
// directly as a type (the same gap gatewayClient.ts documents for Connect's
// `Client<T>` utility type) — deriving instance types from the constructors
// via `InstanceType<typeof X>` sidesteps it, and every type position below
// goes through one of these aliases rather than the bare class name.
type SessionRequestMessage = InstanceType<typeof SessionRequest>;
type SessionResponseMessage = InstanceType<typeof SessionResponse>;
type InvokeMessage = InstanceType<typeof Invoke>;

/**
 * Plain structural mirror of the generated `RegisteredActor` proto message
 * — hand-written rather than derived via `InstanceType<typeof X>` since it
 * crosses this module's own exported surface (`ActorRegistration`) the same
 * way sidecar/gateway.ts's identical type does.
 */
export interface RegisteredActor {
  parentFsmName: string;
  parentFsmVersion: string;
  asyncOperationType: string;
  asyncOperationName: string;
  asyncOperationVersion: string;
  asyncOperationLanguage: string;
}

// Same Deno-vs-tsc inference gap gatewayClient.ts's RawActivityGatewayClient
// works around for Connect's unary `Client<T>` — the bidi-streaming case
// hits it too. Hand-rolled to the exact shape actually called, instead of
// fighting Connect's generic inference under Deno.
interface RawSidecarGatewayClient {
  session(
    requests: AsyncIterable<SessionRequestMessage>,
  ): AsyncIterable<SessionResponseMessage>;
}

export type ActorHandler = (input: unknown) => unknown | Promise<unknown>;

/** One entry from a compiler-generated actor registry (see module doc comment). */
export type ActorRegistration = {
  parentFsmName: string;
  parentFsmVersion: string;
  asyncOperationType: string;
  asyncOperationName: string;
  asyncOperationVersion: string;
  asyncOperationLanguage: string;
  handler: ActorHandler;
};

const DEFAULT_HEARTBEAT_MS = 5_000;

export interface ActorWorkerOptions {
  workerId: string;
  language: string;
  gatewaySocketPath: string;
  heartbeatMs?: number;
}

function actorKey(reg: {
  parentFsmName: string;
  parentFsmVersion: string;
  asyncOperationType: string;
  asyncOperationName: string;
  asyncOperationVersion: string;
  asyncOperationLanguage: string;
}): string {
  return `${reg.parentFsmName}@${reg.parentFsmVersion}@${reg.asyncOperationType}@${reg.asyncOperationName}@${reg.asyncOperationVersion}@${reg.asyncOperationLanguage}`;
}

function parseInputJson(json: string): unknown {
  if (!json.trim()) {
    return null;
  }
  return JSON.parse(json);
}

/**
 * Minimal async push queue feeding this worker's outgoing SessionRequest
 * stream — `run()`/`heartbeatLoop()`/`handleInvoke()` push register,
 * heartbeat, invoke_result, and invoke_error messages onto it; the transport
 * drains it as the actual HTTP/2 request stream. Mirrors
 * sidecar/gateway.ts's identically-shaped queue on the server side — kept as
 * a separate copy rather than a shared import so this SDK stays
 * self-contained the way the Python/Rust/Go worker SDKs necessarily are.
 */
class AsyncQueue<T> implements AsyncIterable<T> {
  private readonly buffered: T[] = [];
  private readonly waiting: Array<(result: IteratorResult<T>) => void> = [];
  private closed = false;

  push(item: T): void {
    if (this.closed) return;
    const next = this.waiting.shift();
    if (next) {
      next({ value: item, done: false });
      return;
    }
    this.buffered.push(item);
  }

  close(): void {
    if (this.closed) return;
    this.closed = true;
    for (const resolve of this.waiting.splice(0)) {
      resolve({ value: undefined, done: true });
    }
  }

  [Symbol.asyncIterator](): AsyncIterator<T> {
    return {
      next: (): Promise<IteratorResult<T>> => {
        if (this.buffered.length > 0) {
          return Promise.resolve({
            value: this.buffered.shift()!,
            done: false,
          });
        }
        if (this.closed) {
          return Promise.resolve({ value: undefined, done: true });
        }
        return new Promise((resolve) => this.waiting.push(resolve));
      },
      // connect-node's client transport wraps the request iterable with its
      // own abort handling, which requires the full async-iterator protocol
      // (native async generators get `throw`/`return` for free; this
      // hand-rolled queue needs them spelled out) — without these it fails
      // with "AsyncIterable does not implement throw" as soon as a call
      // completes or is cancelled.
      return: (value?: T): Promise<IteratorResult<T>> => {
        this.close();
        return Promise.resolve({ value: value as T, done: true });
      },
      throw: (error?: unknown): Promise<IteratorResult<T>> => {
        this.close();
        return Promise.reject(error);
      },
    };
  }
}

// Connects to the gateway's sidecar socket, registers `registrations`, and
// serves invoke requests until the gateway ends the stream or `stop()` is
// called.
export class ActorWorker {
  private outbox: AsyncQueue<SessionRequestMessage> | null = null;
  private stopped = false;
  private readonly handlers = new Map<string, ActorHandler>();

  constructor(
    private readonly options: ActorWorkerOptions,
    private readonly registrations: ActorRegistration[],
  ) {}

  async run(): Promise<void> {
    if (this.registrations.length === 0) {
      throw new Error("no actors to register, refusing to start worker");
    }

    const registeredActors: RegisteredActor[] = [];
    for (const reg of this.registrations) {
      this.handlers.set(actorKey(reg), reg.handler);
      registeredActors.push({
        parentFsmName: reg.parentFsmName,
        parentFsmVersion: reg.parentFsmVersion,
        asyncOperationType: reg.asyncOperationType,
        asyncOperationName: reg.asyncOperationName,
        asyncOperationVersion: reg.asyncOperationVersion,
        asyncOperationLanguage: reg.asyncOperationLanguage,
      });
    }

    const sessionManager = new Http2SessionManager(
      "http://localhost",
      undefined,
      {
        createConnection: () => net.connect(this.options.gatewaySocketPath),
      },
    );
    const transport = createGrpcTransport({
      baseUrl: "http://localhost",
      httpVersion: "2",
      sessionManager,
    });
    const client = createClient(
      SidecarGatewayService,
      transport,
    ) as unknown as RawSidecarGatewayClient;

    const outbox = new AsyncQueue<SessionRequestMessage>();
    this.outbox = outbox;

    outbox.push(
      new SessionRequest({
        payload: {
          case: "register",
          value: new Register({
            workerId: this.options.workerId,
            language: this.options.language,
            protocolVersion: "1.0",
            actors: registeredActors,
          }),
        },
      }),
    );

    const responses = client.session(outbox);
    const iterator = responses[Symbol.asyncIterator]();

    const first = await iterator.next();
    if (first.done || first.value.payload.case !== "registerAck") {
      throw new Error(
        `expected register_ack but got ${
          first.done ? "EOF" : first.value.payload.case
        }`,
      );
    }
    if (!first.value.payload.value.accepted) {
      throw new Error("gateway rejected registration");
    }

    logger.info(
      "Worker {workerId} registered {count} actor(s) with the gateway",
      { workerId: this.options.workerId, count: registeredActors.length },
    );

    const heartbeat = this.heartbeatLoop();

    try {
      await this.serveLoop(iterator);
    } finally {
      this.stopped = true;
      await heartbeat.catch(() => {});
      outbox.push(
        new SessionRequest({
          payload: {
            case: "unregister",
            value: new Unregister({ workerId: this.options.workerId }),
          },
        }),
      );
      outbox.close();
    }
  }

  stop(): void {
    if (this.stopped) return;
    this.stopped = true;
    this.outbox?.push(
      new SessionRequest({
        payload: {
          case: "unregister",
          value: new Unregister({ workerId: this.options.workerId }),
        },
      }),
    );
    this.outbox?.close();
  }

  private async heartbeatLoop(): Promise<void> {
    const intervalMs = this.options.heartbeatMs ?? DEFAULT_HEARTBEAT_MS;
    while (!this.stopped) {
      await new Promise((resolve) => setTimeout(resolve, intervalMs));
      if (this.stopped) {
        break;
      }
      this.outbox?.push(
        new SessionRequest({
          payload: {
            case: "heartbeat",
            value: new Heartbeat({ workerId: this.options.workerId }),
          },
        }),
      );
    }
  }

  private async serveLoop(
    iterator: AsyncIterator<SessionResponseMessage>,
  ): Promise<void> {
    while (!this.stopped) {
      const { value, done } = await iterator.next();
      if (done) {
        break;
      }
      if (value.payload.case === "cancel") {
        continue;
      }
      if (value.payload.case !== "invoke") {
        continue;
      }
      await this.handleInvoke(value.payload.value);
    }
  }

  private async handleInvoke(body: InvokeMessage): Promise<void> {
    const key = actorKey({
      parentFsmName: body.parentFsmName,
      parentFsmVersion: body.parentFsmVersion,
      asyncOperationType: body.asyncOperationType,
      asyncOperationName: body.asyncOperationName,
      asyncOperationVersion: body.asyncOperationVersion,
      asyncOperationLanguage: body.asyncOperationLanguage,
    });
    const handler = this.handlers.get(key);
    const started = performance.now();

    if (!handler) {
      this.sendError(body.invokeId, "NOT_FOUND", `actor not found: ${key}`);
      return;
    }

    try {
      const output = await Promise.resolve(
        handler(parseInputJson(body.inputJson)),
      );
      const durationMs = Math.max(0, Math.round(performance.now() - started));
      this.outbox?.push(
        new SessionRequest({
          payload: {
            case: "invokeResult",
            value: new InvokeResult({
              invokeId: body.invokeId,
              outputJson: JSON.stringify(output ?? null),
              durationMs,
            }),
          },
        }),
      );
    } catch (error) {
      this.sendError(
        body.invokeId,
        "INTERNAL",
        error instanceof Error ? error.message : "unknown worker error",
      );
    }
  }

  private sendError(invokeId: string, code: string, message: string): void {
    this.outbox?.push(
      new SessionRequest({
        payload: {
          case: "invokeError",
          value: new InvokeError({
            invokeId,
            error: new InvokeErrorDetail({ code, message, retriable: false }),
          }),
        },
      }),
    );
  }
}
