import { build, emptyDir } from "@deno/dnt";

await emptyDir("./dist");

const packageVersion = Deno.args[0]?.replace(/^v/, "") ?? "0.0.0";

// All three CLIs' --version flag needs this build's actual version string,
// which deno.json only has for the Deno-native path — generate the
// npm-build variant of src/cli/version.ts fresh on every build:npm run
// rather than hand-maintaining it (see .gitignore: this file isn't
// committed, since the version differs per release). Same pattern as
// fsm-compiler-ts's build-npm.ts (#258).
await Deno.writeTextFile(
  "./src/cli/version.node.ts",
  `// Auto-generated by scripts/build-npm.ts for this build only — not committed, do not edit.\nexport const PACKAGE_VERSION: string = ${
    JSON.stringify(packageVersion)
  };\n`,
);

// @pgfsm/db is published to npm independently — map it to the real npm
// dependency instead of letting dnt inline its source, so a fix published
// there reaches this package via semver instead of requiring a republish
// here too. Version is read from its own deno.json rather than hardcoded, so
// it can't silently drift from whatever this build actually resolved
// locally. Same pattern as fsm-compiler-ts's build-npm.ts mapping @pgfsm/db
// (#250).
const dbDenoJson = JSON.parse(
  await Deno.readTextFile("../fsm-core-db-ts/deno.json"),
);
const dbVersionRange = `^${dbDenoJson.version}`;

// @pgfsm/logging is published to npm independently too (#293) — same
// real-dependency treatment as @pgfsm/db above.
const loggingDenoJson = JSON.parse(
  await Deno.readTextFile("../fsm-logging-ts/deno.json"),
);
const loggingVersionRange = `^${loggingDenoJson.version}`;

await build({
  entryPoints: [
    "./src/index.ts",
    { kind: "bin", name: "fsmscheduler", path: "./src/cli/fsmscheduler.ts" },
    { kind: "bin", name: "fsmctl", path: "./src/cli/fsmctl.ts" },
    { kind: "bin", name: "pgcron", path: "./src/cli/pgcron.ts" },
  ],
  outDir: "./dist",
  shims: {
    deno: true,
  },
  // Each CLI's help text shows how to invoke it, and --version prints this
  // build's version — both differ between this Deno source and the
  // published npm CLI. Runtime detection doesn't work here (see
  // fsm-compiler-ts's build-npm.ts, #254/#258, for why) — swap the whole
  // module instead, one invocation-text pair per bin since each bin's
  // correct npm invocation differs by name.
  mappings: {
    "./src/cli/fsmscheduler-invocation.ts":
      "./src/cli/fsmscheduler-invocation.node.ts",
    "./src/cli/fsmctl-invocation.ts": "./src/cli/fsmctl-invocation.node.ts",
    "./src/cli/pgcron-invocation.ts": "./src/cli/pgcron-invocation.node.ts",
    "./src/cli/version.ts": "./src/cli/version.node.ts",
    "@pgfsm/db": { name: "@pgfsm/db", version: dbVersionRange },
    "@pgfsm/db/database.types": {
      name: "@pgfsm/db",
      version: dbVersionRange,
      subPath: "database.types",
    },
    "@pgfsm/logging": { name: "@pgfsm/logging", version: loggingVersionRange },
  },
  package: {
    name: "@pgfsm/sync-worker",
    version: packageVersion,
    description:
      "Out-of-band worker fleet (fsmscheduler/fsmctl/pgcron) driving FSM instances for PostgreSQL-backed state machines",
    license: "Apache-2.0",
    // pg ships no types of its own; dnt only auto-installs packages that
    // are themselves import specifiers, so without this the type-check
    // pass can't resolve `import ... from "pg"` (deno.json's own
    // "@types/pg" import mapping isn't picked up the same way here).
    devDependencies: {
      "@types/pg": "^8.18.0",
    },
  },
  compilerOptions: {
    lib: ["ES2022", "DOM"],
    target: "ES2022",
  },
  postBuild() {
    if (Deno.args.includes("--copy-readme")) {
      Deno.copyFileSync("README.md", "dist/README.md");
    }
  },
});
