import { build, emptyDir } from "@deno/dnt";

await emptyDir("./dist");

const packageVersion = Deno.args[0]?.replace(/^v/, "") ?? "0.0.0";

// --version prints this build's version; deno.json only has it for the
// Deno-native path, so generate the npm variant of src/version.ts fresh on
// every build (not committed -- see .gitignore), same as @pgfsm/compiler.
await Deno.writeTextFile(
  "./src/version.node.ts",
  `// Auto-generated by scripts/build-npm.ts for this build only — not committed, do not edit.\nexport const PACKAGE_VERSION: string = ${
    JSON.stringify(packageVersion)
  };\n`,
);

// @pgfsm/compiler and @pgfsm/logging are published independently: map them
// to real npm dependencies instead of letting dnt inline their source, with
// ranges read from each package's own deno.json so they can't drift (same
// pattern as fsm-devstack-ts's build-npm.ts).
//
// @pgfsm/cli needs a compiler release that includes #376/#381
// (generateAll's overwrite option, scaffoldWorkerProjects, ...). To try the
// CLI under Node before that release exists, build the compiler first
// (`deno task build:npm` in ../fsm-compiler-ts) and set
// PGFSM_LOCAL_COMPILER=1: the dependency then points at that local build.
const compilerDenoJson = JSON.parse(
  await Deno.readTextFile("../fsm-compiler-ts/deno.json"),
);
const compilerVersion = Deno.env.get("PGFSM_LOCAL_COMPILER")
  ? `file:${new URL("../../fsm-compiler-ts/dist", import.meta.url).pathname}`
  : `^${compilerDenoJson.version}`;
const loggingDenoJson = JSON.parse(
  await Deno.readTextFile("../fsm-logging-ts/deno.json"),
);

await build({
  entryPoints: [
    "./src/index.ts",
    { kind: "bin", name: "pgfsm", path: "./src/cli/pgfsm.ts" },
  ],
  outDir: "./dist",
  shims: { deno: true },
  mappings: {
    "./src/version.ts": "./src/version.node.ts",
    "@pgfsm/compiler": { name: "@pgfsm/compiler", version: compilerVersion },
    "@pgfsm/logging": {
      name: "@pgfsm/logging",
      version: `^${loggingDenoJson.version}`,
    },
  },
  // Tests drive the Deno-native CLI as a subprocess; nothing to ship.
  test: false,
  package: {
    name: "@pgfsm/cli",
    version: packageVersion,
    description:
      "pgfsm: create an FSM worker project from a folder, fsm.json or machine.ts, and add FSMs to it — npx @pgfsm/cli",
    license: "Apache-2.0",
    repository: {
      type: "git",
      url: "git+https://github.com/pgfsm/fsm.git",
      directory: "packages/fsm-cli-ts",
    },
    engines: {
      // Default TypeScript type stripping, so a machine.ts source can be
      // imported without a loader.
      node: ">=22.18.0",
    },
  },
  compilerOptions: {
    lib: ["ES2022", "DOM"],
    target: "ES2022",
  },
  postBuild() {
    if (Deno.args.includes("--copy-readme")) {
      Deno.copyFileSync("README.md", "dist/README.md");
    }
  },
});
