// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import {
  loadWork,
  maxConcurrency as maxConcurrency_loadWork,
} from "./actors/loadWork/loadWork.ts";

export type ActorRegistration = {
  parentFsmName: string;
  parentFsmVersion: string;
  asyncOperationType: string;
  asyncOperationName: string;
  asyncOperationVersion: string;
  asyncOperationLanguage: string;
  /** The actor's own limit, from its stub; unset falls back to the worker's --max-concurrency. */
  maxConcurrency?: number;
  handler: (input: unknown) => unknown;
};

export const ACTOR_REGISTRATIONS: ActorRegistration[] = [
  {
    parentFsmName: "loadTest",
    parentFsmVersion: "v01",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "loadWork",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    maxConcurrency: maxConcurrency_loadWork,
    handler: loadWork,
  },
];
