// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { fetchInterestRateOptions } from "./fetchInterestRateOptions/fetchInterestRateOptions.ts";
import { verifyCredentials } from "./verifyCredentials/verifyCredentials.ts";
import { CheckingCreditScores3parallel } from "./CheckingCreditScores3parallel/CheckingCreditScores3parallel.ts";
import { checkReportsTable } from "./checkReportsTable/checkReportsTable.ts";
import { checkBureau } from "./checkBureau/checkBureau.ts";
import { determineMiddleScore } from "./determineMiddleScore/determineMiddleScore.ts";
import { generateInterestRates } from "./generateInterestRates/generateInterestRates.ts";

export type ActorRegistration = {
  parentFsmName: string;
  parentFsmVersion: string;
  asyncOperationType: string;
  asyncOperationName: string;
  asyncOperationVersion: string;
  asyncOperationLanguage: string;
  handler: (input: unknown) => unknown;
};

export const ACTOR_REGISTRATIONS: ActorRegistration[] = [
  {
    parentFsmName: "creditCheck",
    parentFsmVersion: "v02",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "fetchInterestRateOptions",
    asyncOperationVersion: "v02",
    asyncOperationLanguage: "typescript",
    handler: fetchInterestRateOptions,
  },
  {
    parentFsmName: "creditCheck",
    parentFsmVersion: "v02",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "verifyCredentials",
    asyncOperationVersion: "v02",
    asyncOperationLanguage: "typescript",
    handler: verifyCredentials,
  },
  {
    parentFsmName: "creditCheck",
    parentFsmVersion: "v02",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "CheckingCreditScores3parallel",
    asyncOperationVersion: "v02",
    asyncOperationLanguage: "typescript",
    handler: CheckingCreditScores3parallel,
  },
  {
    parentFsmName: "creditCheck",
    parentFsmVersion: "v02",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "checkReportsTable",
    asyncOperationVersion: "v02",
    asyncOperationLanguage: "typescript",
    handler: checkReportsTable,
  },
  {
    parentFsmName: "creditCheck",
    parentFsmVersion: "v02",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "checkBureau",
    asyncOperationVersion: "v02",
    asyncOperationLanguage: "typescript",
    handler: checkBureau,
  },
  {
    parentFsmName: "creditCheck",
    parentFsmVersion: "v02",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "determineMiddleScore",
    asyncOperationVersion: "v02",
    asyncOperationLanguage: "typescript",
    handler: determineMiddleScore,
  },
  {
    parentFsmName: "creditCheck",
    parentFsmVersion: "v02",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "generateInterestRates",
    asyncOperationVersion: "v02",
    asyncOperationLanguage: "typescript",
    handler: generateInterestRates,
  },
];
