// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
// worker-sdk/go reference binary — Go reference worker for the Activity
// Gateway.
//
// Go counterpart of ../typescript/cli.ts and ../python/cli.py: actors come
// from a compiler-generated registry
// (fsm-core-example/go-actors-registry-generated, see fsm-compiler-ts's
// writeAggregateGoRegistry), not a folder scan. Go has no runtime mechanism
// to load a function out of a .go source file the way import() (TS) or
// importlib (Python) can, so the registry's handlers are real functions
// linked into this binary via a require/replace directive in go.mod (see
// that file) — "verification" happens at compile time (it wouldn't build if
// an actor's function didn't exist or had the wrong signature), not at
// worker startup.
//
// USAGE
//
//	go run . [options]
//
// OPTIONS
//
//	--gateway-socket <path>   Sidecar socket to connect to (default: /tmp/pgfsm-activity-gateway-workers.sock)
//	--worker-id <id>          Stable worker identity (default: go-<pid>)
//	--heartbeat-ms <ms>       Heartbeat interval (default: 5000)
package main

import (
	"flag"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	generatedregistry "fsm-core-example/go-actors-registry-generated"
)

func registrationsFromGenerated() []ActorRegistration {
	generated := generatedregistry.ActorRegistrations()
	registrations := make([]ActorRegistration, 0, len(generated))
	for _, reg := range generated {
		registrations = append(registrations, ActorRegistration{
			Meta: RegisteredActor{
				ParentFsmName:    reg.ParentFsmName,
				ParentFsmVersion: reg.ParentFsmVersion,
				AsyncOperationType:          reg.AsyncOperationType,
				AsyncOperationName:          reg.AsyncOperationName,
				AsyncOperationVersion:       reg.AsyncOperationVersion,
				AsyncOperationLanguage:      reg.AsyncOperationLanguage,
			},
			Handler: reg.Handler,
		})
	}
	return registrations
}

func main() {
	gatewaySocket := flag.String("gateway-socket", "/tmp/pgfsm-activity-gateway-workers.sock", "Sidecar socket to connect to")
	workerID := flag.String("worker-id", "", "Stable worker identity (default: go-<pid>)")
	heartbeatMs := flag.Int("heartbeat-ms", 5000, "Heartbeat interval")
	flag.Parse()

	id := *workerID
	if id == "" {
		id = fmt.Sprintf("go-%d", os.Getpid())
	}

	registrations := registrationsFromGenerated()
	fmt.Printf("%d actor(s) compiled into this registry\n", len(registrations))
	for _, reg := range registrations {
		fmt.Printf("  + %s@%s (parent %s@%s)\n", reg.Meta.AsyncOperationName, reg.Meta.AsyncOperationVersion, reg.Meta.ParentFsmName, reg.Meta.ParentFsmVersion)
	}

	if len(registrations) == 0 {
		fmt.Fprintln(os.Stderr, "No actors in the registry, refusing to start worker")
		os.Exit(1)
	}

	worker := NewActorWorker(ActorWorkerOptions{
		WorkerID:          id,
		GatewaySocketPath: *gatewaySocket,
		HeartbeatMs:       *heartbeatMs,
	}, registrations)

	signals := make(chan os.Signal, 1)
	signal.Notify(signals, os.Interrupt, syscall.SIGTERM)
	go func() {
		<-signals
		fmt.Println("Shutdown requested — stopping worker...")
		worker.Stop()
	}()

	fmt.Printf("Starting worker %s: gateway-socket=%s\n", id, *gatewaySocket)
	if err := worker.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "Worker %s failed: %v\n", id, err)
		os.Exit(1)
	}
	fmt.Printf("Worker %s stopped.\n", id)
}
