// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { recordFinished } from "./actions/recordFinished/recordFinished.ts";

export type SyncOperationRegistration = {
  fsmName: string;
  fsmVersion: string;
  syncOperationType: "action" | "guard" | "delay";
  syncOperationName: string;
  syncOperationLanguage: string;
  handler: (...args: unknown[]) => unknown;
};

export type FsmDefinitionDigest = {
  fsmName: string;
  fsmVersion: string;
  fsmJsonSha256: string;
};

// Canonical (RFC 8785) SHA-256 of the fsm.json this registry was generated
// from; the fsmlet refuses to start if the loaded definition differs.
export const FSM_DEFINITION: FsmDefinitionDigest = {
  fsmName: "loadTest",
  fsmVersion: "v01",
  fsmJsonSha256:
    "97d630aad6a7c6a1920ffb8ebf33066bf20dfe7502700caddf302269d95b41da",
};

export const SYNC_OPERATION_REGISTRATIONS: SyncOperationRegistration[] = [
  {
    fsmName: "loadTest",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "recordFinished",
    syncOperationLanguage: "typescript",
    handler: recordFinished,
  },
];
