// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { assignSSN } from "./actions/assignSSN/assignSSN.ts";
import { assignFirstName } from "./actions/assignFirstName/assignFirstName.ts";
import { assignLastName } from "./actions/assignLastName/assignLastName.ts";
import { assignErrorMessage } from "./actions/assignErrorMessage/assignErrorMessage.ts";
import { assignCreditScoreError } from "./actions/assignCreditScoreError/assignCreditScoreError.ts";
import { assignEquiGavinScore } from "./actions/assignEquiGavinScore/assignEquiGavinScore.ts";
import { saveReportEquiGavin } from "./actions/saveReportEquiGavin/saveReportEquiGavin.ts";
import { assignEquiGavinScoreFetch } from "./actions/assignEquiGavinScoreFetch/assignEquiGavinScoreFetch.ts";
import { assignGavUnionScore } from "./actions/assignGavUnionScore/assignGavUnionScore.ts";
import { saveReportGavUnion } from "./actions/saveReportGavUnion/saveReportGavUnion.ts";
import { assignGavUnionScoreFetch } from "./actions/assignGavUnionScoreFetch/assignGavUnionScoreFetch.ts";
import { assignGavperianScore } from "./actions/assignGavperianScore/assignGavperianScore.ts";
import { saveReportGavperian } from "./actions/saveReportGavperian/saveReportGavperian.ts";
import { assignGavperianScoreFetch } from "./actions/assignGavperianScoreFetch/assignGavperianScoreFetch.ts";
import { assignMiddleScore } from "./actions/assignMiddleScore/assignMiddleScore.ts";
import { saveCreditProfile } from "./actions/saveCreditProfile/saveCreditProfile.ts";
import { assignInterestRateOptions } from "./actions/assignInterestRateOptions/assignInterestRateOptions.ts";
import { emailUser } from "./actions/emailUser/emailUser.ts";
import { emailSalesTeam } from "./actions/emailSalesTeam/emailSalesTeam.ts";
import { allSucceeded } from "./guards/allSucceeded/allSucceeded.ts";
import { equiGavinReportFound } from "./guards/equiGavinReportFound/equiGavinReportFound.ts";
import { gavUnionReportFound } from "./guards/gavUnionReportFound/gavUnionReportFound.ts";
import { gavperianReportFound } from "./guards/gavperianReportFound/gavperianReportFound.ts";

export type SyncOperationRegistration = {
  fsmName: string;
  fsmVersion: string;
  syncOperationType: "action" | "guard" | "delay";
  syncOperationName: string;
  syncOperationLanguage: string;
  handler: (...args: unknown[]) => unknown;
};

export type FsmDefinitionDigest = {
  fsmName: string;
  fsmVersion: string;
  fsmJsonSha256: string;
};

// Canonical (RFC 8785) SHA-256 of the fsm.json this registry was generated
// from; the fsmlet refuses to start if the loaded definition differs.
export const FSM_DEFINITION: FsmDefinitionDigest = {
  fsmName: "creditCheck",
  fsmVersion: "v01",
  fsmJsonSha256:
    "3025c74bf6e8186718ddd3dff4fbd032e22d1535cacb941911055417142022ec",
};

export const SYNC_OPERATION_REGISTRATIONS: SyncOperationRegistration[] = [
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignSSN",
    syncOperationLanguage: "typescript",
    handler: assignSSN,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignFirstName",
    syncOperationLanguage: "typescript",
    handler: assignFirstName,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignLastName",
    syncOperationLanguage: "typescript",
    handler: assignLastName,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignErrorMessage",
    syncOperationLanguage: "typescript",
    handler: assignErrorMessage,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignCreditScoreError",
    syncOperationLanguage: "typescript",
    handler: assignCreditScoreError,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignEquiGavinScore",
    syncOperationLanguage: "typescript",
    handler: assignEquiGavinScore,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "saveReportEquiGavin",
    syncOperationLanguage: "typescript",
    handler: saveReportEquiGavin,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignEquiGavinScoreFetch",
    syncOperationLanguage: "typescript",
    handler: assignEquiGavinScoreFetch,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignGavUnionScore",
    syncOperationLanguage: "typescript",
    handler: assignGavUnionScore,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "saveReportGavUnion",
    syncOperationLanguage: "typescript",
    handler: saveReportGavUnion,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignGavUnionScoreFetch",
    syncOperationLanguage: "typescript",
    handler: assignGavUnionScoreFetch,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignGavperianScore",
    syncOperationLanguage: "typescript",
    handler: assignGavperianScore,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "saveReportGavperian",
    syncOperationLanguage: "typescript",
    handler: saveReportGavperian,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignGavperianScoreFetch",
    syncOperationLanguage: "typescript",
    handler: assignGavperianScoreFetch,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignMiddleScore",
    syncOperationLanguage: "typescript",
    handler: assignMiddleScore,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "saveCreditProfile",
    syncOperationLanguage: "typescript",
    handler: saveCreditProfile,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignInterestRateOptions",
    syncOperationLanguage: "typescript",
    handler: assignInterestRateOptions,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "emailUser",
    syncOperationLanguage: "typescript",
    handler: emailUser,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "emailSalesTeam",
    syncOperationLanguage: "typescript",
    handler: emailSalesTeam,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "guard",
    syncOperationName: "allSucceeded",
    syncOperationLanguage: "typescript",
    handler: allSucceeded,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "guard",
    syncOperationName: "equiGavinReportFound",
    syncOperationLanguage: "typescript",
    handler: equiGavinReportFound,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "guard",
    syncOperationName: "gavUnionReportFound",
    syncOperationLanguage: "typescript",
    handler: gavUnionReportFound,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v01",
    syncOperationType: "guard",
    syncOperationName: "gavperianReportFound",
    syncOperationLanguage: "typescript",
    handler: gavperianReportFound,
  },
];
