import { build, emptyDir } from "@deno/dnt";

await emptyDir("./dist");

const packageVersion = Deno.args[0]?.replace(/^v/, "") ?? "0.0.0";

// The CLI's --version flag needs this build's actual version string, which
// deno.json only has for the Deno-native path — generate the npm-build
// variant of src/cli/version.ts fresh on every build:npm run rather than
// hand-maintaining it (see .gitignore: this file isn't committed, since the
// version differs per release).
await Deno.writeTextFile(
  "./src/cli/version.node.ts",
  `// Auto-generated by scripts/build-npm.ts for this build only — not committed, do not edit.\nexport const PACKAGE_VERSION: string = ${
    JSON.stringify(packageVersion)
  };\n`,
);

// @pgfsm/db and @pgfsm/logging are both published to npm independently —
// map them to their real npm dependencies instead of letting dnt inline
// their source, so a fix published there reaches this package via semver
// instead of requiring a republish here too. Version is read from each
// one's own deno.json rather than hardcoded, so it can't silently drift
// from whatever this build actually resolved locally. Same pattern as
// fsm-sync-worker-ts's build-npm.ts mapping @pgfsm/compiler (#283).
const dbDenoJson = JSON.parse(
  await Deno.readTextFile("../fsm-core-db-ts/deno.json"),
);
const dbVersionRange = `^${dbDenoJson.version}`;

const loggingDenoJson = JSON.parse(
  await Deno.readTextFile("../fsm-logging-ts/deno.json"),
);
const loggingVersionRange = `^${loggingDenoJson.version}`;

await build({
  entryPoints: [
    "./src/index.ts",
    { kind: "bin", name: "fsm-compiler", path: "./src/cli/index.ts" },
    // Nothing statically imports this — it's only referenced by the
    // runtime string module.register() passes in
    // src/import-resolution.node.ts (see #270) — so it must be listed
    // explicitly or dnt's graph walker never transpiles/emits it.
    "./src/cli/loader.node.ts",
  ],
  outDir: "./dist",
  shims: {
    deno: true,
  },
  // The CLI's help text shows how to invoke it, and --version prints this
  // build's version — both differ between this Deno source (`deno run ...`,
  // deno.json's version field) and the published npm CLI (`npx ...`, the
  // version this build was invoked with). Runtime detection
  // (Deno.version/mainModule/execPath) doesn't work here — `shims: { deno:
  // true }` above provides a Deno global under Node too, so those signals
  // are present (or, for execPath, actively misleading) under both targets.
  // Swap the whole module instead: see src/cli/invocation.ts /
  // invocation.node.ts and src/cli/version.ts / version.node.ts (generated
  // above).
  mappings: {
    "./src/cli/invocation.ts": "./src/cli/invocation.node.ts",
    "./src/cli/version.ts": "./src/cli/version.node.ts",
    "./src/import-resolution.ts": "./src/import-resolution.node.ts",
    "@pgfsm/db": { name: "@pgfsm/db", version: dbVersionRange },
    "@pgfsm/db/database.types": {
      name: "@pgfsm/db",
      version: dbVersionRange,
      subPath: "database.types",
    },
    "@pgfsm/logging": { name: "@pgfsm/logging", version: loggingVersionRange },
  },
  // Publishing doesn't need test/*.test.ts bundled into dist — and dnt tries
  // to build them for the CJS target too, which fails on the top-level
  // await in test/cli.test.ts (CJS/UMD can't support it).
  test: false,
  package: {
    name: "@pgfsm/compiler",
    version: packageVersion,
    description: "FSM JSON compiler for PostgreSQL-backed state machines",
    license: "Apache-2.0",
    // pg ships no types of its own; dnt only auto-installs packages that
    // are themselves import specifiers, so without this the type-check
    // pass can't resolve `import ... from "pg"` (deno.json's own
    // "@types/pg" import mapping isn't picked up the same way here).
    devDependencies: {
      "@types/pg": "^8.18.0",
    },
    // src/cli/loader.node.ts registers itself via node:module's register(),
    // which needs Node 20.6+ (see #270).
    engines: {
      node: ">=20.6.0",
    },
  },
  compilerOptions: {
    lib: ["ES2022", "DOM"],
    target: "ES2022",
  },
  postBuild() {
    if (Deno.args.includes("--copy-readme")) {
      Deno.copyFileSync("README.md", "dist/README.md");
    }
  },
});
