// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { verifyCredentials } from "./actors/verifyCredentials/verifyCredentials.ts";
import { checkReportsTable } from "./actors/checkReportsTable/checkReportsTable.ts";
import {
  checkBureau,
  maxConcurrency as maxConcurrency_checkBureau,
} from "./actors/checkBureau/checkBureau.ts";
import { determineMiddleScore } from "./actors/determineMiddleScore/determineMiddleScore.ts";
import { generateInterestRates } from "./actors/generateInterestRates/generateInterestRates.ts";

export type ActorRegistration = {
  parentFsmName: string;
  parentFsmVersion: string;
  asyncOperationType: string;
  asyncOperationName: string;
  asyncOperationVersion: string;
  asyncOperationLanguage: string;
  /** The actor's own limit, from its stub; unset falls back to the worker's --max-concurrency. */
  maxConcurrency?: number;
  handler: (input: unknown) => unknown;
};

export const ACTOR_REGISTRATIONS: ActorRegistration[] = [
  {
    parentFsmName: "creditCheck",
    parentFsmVersion: "v01",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "verifyCredentials",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    handler: verifyCredentials,
  },
  {
    parentFsmName: "creditCheck",
    parentFsmVersion: "v01",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "checkReportsTable",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    handler: checkReportsTable,
  },
  {
    parentFsmName: "creditCheck",
    parentFsmVersion: "v01",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "checkBureau",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    maxConcurrency: maxConcurrency_checkBureau,
    handler: checkBureau,
  },
  {
    parentFsmName: "creditCheck",
    parentFsmVersion: "v01",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "determineMiddleScore",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    handler: determineMiddleScore,
  },
  {
    parentFsmName: "creditCheck",
    parentFsmVersion: "v01",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "generateInterestRates",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    handler: generateInterestRates,
  },
];
