import { build, emptyDir } from "@deno/dnt";

await emptyDir("./dist");

const packageVersion = Deno.args[0]?.replace(/^v/, "") ?? "0.0.0";

// --version prints this build's version; deno.json only has it for the
// Deno-native path, so generate the npm variant of src/version.ts fresh on
// every build (not committed -- see .gitignore), same as @pgfsm/cli.
await Deno.writeTextFile(
  "./src/version.node.ts",
  `// Auto-generated by scripts/build-npm.ts for this build only — not committed, do not edit.\nexport const PACKAGE_VERSION: string = ${
    JSON.stringify(packageVersion)
  };\n`,
);

// @pgfsm/db and @pgfsm/logging are published independently: map them to
// real npm dependencies instead of letting dnt inline their source, with
// ranges read from each package's own deno.json so they can't drift (same
// pattern as @pgfsm/cli). @pgfsm/db is this package's compatibility axis
// (SPEC-005): pgfsmctl works against the fsm_core functions that db version
// expects.
//
// To build against @pgfsm/db changes that aren't published yet, build db
// first (`deno task build:npm <version>` in ../fsm-core-db-ts) and set
// PGFSM_LOCAL_DB=1: the dependency then points at that local build (same
// escape hatch as @pgfsm/cli's PGFSM_LOCAL_COMPILER).
const dbDenoJson = JSON.parse(
  await Deno.readTextFile("../fsm-core-db-ts/deno.json"),
);
const dbVersionRange = Deno.env.get("PGFSM_LOCAL_DB")
  ? `file:${new URL("../../fsm-core-db-ts/dist", import.meta.url).pathname}`
  : `^${dbDenoJson.version}`;
const loggingDenoJson = JSON.parse(
  await Deno.readTextFile("../fsm-logging-ts/deno.json"),
);

await build({
  entryPoints: [
    "./src/index.ts",
    { kind: "bin", name: "pgfsmctl", path: "./src/cli/pgfsmctl.ts" },
  ],
  outDir: "./dist",
  shims: { deno: true },
  mappings: {
    "./src/version.ts": "./src/version.node.ts",
    "./src/invocation.ts": "./src/invocation.node.ts",
    "@pgfsm/db": { name: "@pgfsm/db", version: dbVersionRange },
    "@pgfsm/logging": {
      name: "@pgfsm/logging",
      version: `^${loggingDenoJson.version}`,
    },
  },
  // Tests drive the Deno-native CLI as a subprocess; nothing to ship.
  test: false,
  package: {
    name: "@pgfsm/ctl",
    version: packageVersion,
    description:
      "pgfsmctl: operate a pgfsm database — pg_cron scheduler registration, FSM instance create/resume/send/stop — npx @pgfsm/ctl",
    license: "Apache-2.0",
    repository: {
      type: "git",
      url: "git+https://github.com/pgfsm/fsm.git",
      directory: "packages/fsm-ctl-ts",
    },
    // pg ships no types of its own; dnt only auto-installs packages that
    // are themselves import specifiers (see @pgfsm/sync-worker's
    // build-npm.ts).
    devDependencies: {
      "@types/pg": "^8.18.0",
    },
  },
  compilerOptions: {
    lib: ["ES2022", "DOM"],
    target: "ES2022",
  },
  postBuild() {
    if (Deno.args.includes("--copy-readme")) {
      Deno.copyFileSync("README.md", "dist/README.md");
    }
  },
});
