// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { ACTOR_REGISTRATIONS as loadtest_v01 } from "./loadTest/v01/actor-registry.generated.ts";

export const ACTOR_REGISTRATIONS = [
  ...loadtest_v01,
];
