// AUTO-GENERATED from actors-registry-aggregate.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  "// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\npackage generatedregistry\n\nimport (\n<% for (const imp of it.imports) { -%>\n\t<%~ imp.alias %> \"<%~ imp.modulePath %>\"\n<% } -%>\n)\n\ntype ActorRegistration struct {\n\tParentFsmName    string\n\tParentFsmVersion string\n\tAsyncOperationType          string\n\tAsyncOperationName          string\n\tAsyncOperationVersion       string\n\tAsyncOperationLanguage      string\n\t// MaxConcurrency is the actor's own limit, from its stub's MaxConcurrency;\n\t// 0 falls back to the worker's --max-concurrency.\n\tMaxConcurrency   uint32\n\tHandler          func(input any) (any, error)\n}\n\nfunc ActorRegistrations() []ActorRegistration {\n\treturn []ActorRegistration{\n<% for (const a of it.actors) { -%>\n\t\t{\n\t\t\tParentFsmName:    <%~ JSON.stringify(a.parentFsmName) %>,\n\t\t\tParentFsmVersion: <%~ JSON.stringify(a.parentFsmVersion) %>,\n\t\t\tAsyncOperationType:          <%~ JSON.stringify(a.asyncOperationType) %>,\n\t\t\tAsyncOperationName:          <%~ JSON.stringify(a.asyncOperationName) %>,\n\t\t\tAsyncOperationVersion:       <%~ JSON.stringify(a.asyncOperationVersion) %>,\n\t\t\tAsyncOperationLanguage:      <%~ JSON.stringify(a.asyncOperationLanguage) %>,\n<% if (a.declaresMaxConcurrency) { -%>\n\t\t\tMaxConcurrency:   uint32(<%~ a.alias %>.MaxConcurrency),\n<% } -%>\n\t\t\tHandler:          <%~ a.alias %>.<%~ a.exportedName %>,\n\t\t},\n<% } -%>\n\t}\n}\n",
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
