// AUTO-GENERATED from worker-sdk-main.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n//\n// Go worker for the Activity Gateway: wires this project\'s compiler-generated\n// actor registry into the pgfsm async worker SDK\'s RunActorWorkerCLI (see\n// go.mod for the pinned version).\n//\n// USAGE\n//\n//\tgo run . <list|start> [options]\n//\n// EXAMPLE\n//\n//\tgo run . start --gateway-socket /tmp/pgfsm-activity-gateway-workers.sock\n//\n// The registry package is compiler-generated -- see fsm-compiler-ts\'s\n// writeAggregateGoRegistry. Regenerate with\n// `npx @pgfsm/compiler -c generate-async-logic -f <plugin-root>` after actors\n// change. Go can\'t load actor functions at runtime the way TypeScript/Python\n// can, so they\'re linked into this binary through go.mod\'s require/replace\n// directives: a missing or mistyped actor fails the build, not worker startup.\npackage main\n\nimport (\n\t"os"\n\n\tgeneratedregistry "<%~ it.registryModulePath %>"\n\tasyncworkersdk "<%~ it.sdkModulePath %>"\n)\n\nfunc main() {\n\tgenerated := generatedregistry.ActorRegistrations()\n\tregistrations := make([]asyncworkersdk.ActorRegistration, 0, len(generated))\n\tfor _, reg := range generated {\n\t\tregistrations = append(registrations, asyncworkersdk.NewActorRegistration(\n\t\t\treg.ParentFsmName,\n\t\t\treg.ParentFsmVersion,\n\t\t\treg.AsyncOperationType,\n\t\t\treg.AsyncOperationName,\n\t\t\treg.AsyncOperationVersion,\n\t\t\treg.AsyncOperationLanguage,\n\t\t\treg.Handler,\n\t\t))\n\t}\n\tos.Exit(asyncworkersdk.RunActorWorkerCLI(registrations, os.Args[1:], ""))\n}\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
