// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { rootInterpreterIdSuccess } from "./actions/rootInterpreterIdSuccess/rootInterpreterIdSuccess.ts";
import { rootInterpreterIdError } from "./actions/rootInterpreterIdError/rootInterpreterIdError.ts";
import { verifyCredentialsSuccess } from "./actions/verifyCredentialsSuccess/verifyCredentialsSuccess.ts";
import { CheckingEquiGavinEntry } from "./actions/CheckingEquiGavinEntry/CheckingEquiGavinEntry.ts";
import { CheckingEquiGavinExit } from "./actions/CheckingEquiGavinExit/CheckingEquiGavinExit.ts";
import { CheckingForExistingReportExit } from "./actions/CheckingForExistingReportExit/CheckingForExistingReportExit.ts";
import { equiGavinDBActorSuccess } from "./actions/equiGavinDBActorSuccess/equiGavinDBActorSuccess.ts";
import { saveReport } from "./actions/saveReport/saveReport.ts";
import { equiGavinFetchActorSuccess } from "./actions/equiGavinFetchActorSuccess/equiGavinFetchActorSuccess.ts";
import { CheckingGavUnionExit } from "./actions/CheckingGavUnionExit/CheckingGavUnionExit.ts";
import { gavUnionDBActorSuccess } from "./actions/gavUnionDBActorSuccess/gavUnionDBActorSuccess.ts";
import { FetchingCompleteEntryAction } from "./actions/FetchingCompleteEntryAction/FetchingCompleteEntryAction.ts";
import { gavUnionFetchActorSuccess } from "./actions/gavUnionFetchActorSuccess/gavUnionFetchActorSuccess.ts";
import { CheckingGavperianEntry } from "./actions/CheckingGavperianEntry/CheckingGavperianEntry.ts";
import { gavperianCheckActorSuccess } from "./actions/gavperianCheckActorSuccess/gavperianCheckActorSuccess.ts";
import { checkGavPerianActorSuccess } from "./actions/checkGavPerianActorSuccess/checkGavPerianActorSuccess.ts";
import { saveCreditProfile } from "./actions/saveCreditProfile/saveCreditProfile.ts";
import { generateInterestRatesSuccess } from "./actions/generateInterestRatesSuccess/generateInterestRatesSuccess.ts";
import { emailUser } from "./actions/emailUser/emailUser.ts";
import { emailSalesTeam } from "./actions/emailSalesTeam/emailSalesTeam.ts";
import { allWorkflowStepDoneEntryAction } from "./actions/allWorkflowStepDoneEntryAction/allWorkflowStepDoneEntryAction.ts";
import { delay111111 } from "./delays/111111/111111.ts";
import { delayshort1000delay } from "./delays/short1000delay/short1000delay.ts";
import { delaylogng2000delay } from "./delays/logng2000delay/logng2000delay.ts";
import { delayvc1000delay } from "./delays/vc1000delay/vc1000delay.ts";
import { delayvc2000delay } from "./delays/vc2000delay/vc2000delay.ts";

export type SyncOperationRegistration = {
  fsmName: string;
  fsmVersion: string;
  syncOperationType: "action" | "guard" | "delay";
  syncOperationName: string;
  syncOperationLanguage: string;
  handler: (...args: unknown[]) => unknown;
};

export type FsmDefinitionDigest = {
  fsmName: string;
  fsmVersion: string;
  fsmJsonSha256: string;
};

// Canonical (RFC 8785) SHA-256 of the fsm.json this registry was generated
// from; the fsmlet refuses to start if the loaded definition differs.
export const FSM_DEFINITION: FsmDefinitionDigest = {
  fsmName: "creditCheck",
  fsmVersion: "v02",
  fsmJsonSha256:
    "06f7c1e73f20db29f8be2824b8e10d31a5eb76c24902edee90eaae145a4779f8",
};

export const SYNC_OPERATION_REGISTRATIONS: SyncOperationRegistration[] = [
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "rootInterpreterIdSuccess",
    syncOperationLanguage: "typescript",
    handler: rootInterpreterIdSuccess,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "rootInterpreterIdError",
    syncOperationLanguage: "typescript",
    handler: rootInterpreterIdError,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "verifyCredentialsSuccess",
    syncOperationLanguage: "typescript",
    handler: verifyCredentialsSuccess,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "CheckingEquiGavinEntry",
    syncOperationLanguage: "typescript",
    handler: CheckingEquiGavinEntry,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "CheckingEquiGavinExit",
    syncOperationLanguage: "typescript",
    handler: CheckingEquiGavinExit,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "CheckingForExistingReportExit",
    syncOperationLanguage: "typescript",
    handler: CheckingForExistingReportExit,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "equiGavinDBActorSuccess",
    syncOperationLanguage: "typescript",
    handler: equiGavinDBActorSuccess,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "saveReport",
    syncOperationLanguage: "typescript",
    handler: saveReport,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "equiGavinFetchActorSuccess",
    syncOperationLanguage: "typescript",
    handler: equiGavinFetchActorSuccess,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "CheckingGavUnionExit",
    syncOperationLanguage: "typescript",
    handler: CheckingGavUnionExit,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "gavUnionDBActorSuccess",
    syncOperationLanguage: "typescript",
    handler: gavUnionDBActorSuccess,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "FetchingCompleteEntryAction",
    syncOperationLanguage: "typescript",
    handler: FetchingCompleteEntryAction,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "gavUnionFetchActorSuccess",
    syncOperationLanguage: "typescript",
    handler: gavUnionFetchActorSuccess,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "CheckingGavperianEntry",
    syncOperationLanguage: "typescript",
    handler: CheckingGavperianEntry,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "gavperianCheckActorSuccess",
    syncOperationLanguage: "typescript",
    handler: gavperianCheckActorSuccess,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "checkGavPerianActorSuccess",
    syncOperationLanguage: "typescript",
    handler: checkGavPerianActorSuccess,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "saveCreditProfile",
    syncOperationLanguage: "typescript",
    handler: saveCreditProfile,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "generateInterestRatesSuccess",
    syncOperationLanguage: "typescript",
    handler: generateInterestRatesSuccess,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "emailUser",
    syncOperationLanguage: "typescript",
    handler: emailUser,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "emailSalesTeam",
    syncOperationLanguage: "typescript",
    handler: emailSalesTeam,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "allWorkflowStepDoneEntryAction",
    syncOperationLanguage: "typescript",
    handler: allWorkflowStepDoneEntryAction,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "delay",
    syncOperationName: "111111",
    syncOperationLanguage: "typescript",
    handler: delay111111,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "delay",
    syncOperationName: "short1000delay",
    syncOperationLanguage: "typescript",
    handler: delayshort1000delay,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "delay",
    syncOperationName: "logng2000delay",
    syncOperationLanguage: "typescript",
    handler: delaylogng2000delay,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "delay",
    syncOperationName: "vc1000delay",
    syncOperationLanguage: "typescript",
    handler: delayvc1000delay,
  },
  {
    fsmName: "creditCheck",
    fsmVersion: "v02",
    syncOperationType: "delay",
    syncOperationName: "vc2000delay",
    syncOperationLanguage: "typescript",
    handler: delayvc2000delay,
  },
];
