// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
package generatedregistry

import (
	creditcheck_v01_checkreportstable "debug-only/creditcheck/v01/go/actors/checkreportstable"
)

type ActorRegistration struct {
	ParentFsmName          string
	ParentFsmVersion       string
	AsyncOperationType     string
	AsyncOperationName     string
	AsyncOperationVersion  string
	AsyncOperationLanguage string
	// MaxConcurrency is the actor's own limit, from its stub's MaxConcurrency;
	// 0 falls back to the worker's --max-concurrency.
	MaxConcurrency uint32
	Handler        func(input any) (any, error)
}

func ActorRegistrations() []ActorRegistration {
	return []ActorRegistration{
		{
			ParentFsmName:          "creditCheck",
			ParentFsmVersion:       "v01",
			AsyncOperationType:     "internalAsyncOperation",
			AsyncOperationName:     "CheckReportsTable",
			AsyncOperationVersion:  "v01",
			AsyncOperationLanguage: "go",
			MaxConcurrency:         uint32(creditcheck_v01_checkreportstable.MaxConcurrency),
			Handler:                creditcheck_v01_checkreportstable.CheckReportsTable,
		},
	}
}
