// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { checkTirePressure } from "./actors/checkTirePressure/checkTirePressure.ts";
import { checkOilPressure } from "./actors/checkOilPressure/checkOilPressure.ts";
import { checkCoolantLevel } from "./actors/checkCoolantLevel/checkCoolantLevel.ts";
import { checkBattery } from "./actors/checkBattery/checkBattery.ts";

export type ActorRegistration = {
  parentFsmName: string;
  parentFsmVersion: string;
  asyncOperationType: string;
  asyncOperationName: string;
  asyncOperationVersion: string;
  asyncOperationLanguage: string;
  handler: (input: unknown) => unknown;
};

export const ACTOR_REGISTRATIONS: ActorRegistration[] = [
  {
    parentFsmName: "vitalsWorkflow",
    parentFsmVersion: "v01",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "checkTirePressure",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    handler: checkTirePressure,
  },
  {
    parentFsmName: "vitalsWorkflow",
    parentFsmVersion: "v01",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "checkOilPressure",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    handler: checkOilPressure,
  },
  {
    parentFsmName: "vitalsWorkflow",
    parentFsmVersion: "v01",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "checkCoolantLevel",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    handler: checkCoolantLevel,
  },
  {
    parentFsmName: "vitalsWorkflow",
    parentFsmVersion: "v01",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "checkBattery",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    handler: checkBattery,
  },
];
