// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
// Go worker SDK: connects to the gateway's sidecar Unix socket via the
// generated pgfsm.sidecargateway.v1.SidecarGatewayService bidi-streaming
// client (packages/fsm-proto-codegen/gen/go/, from
// packages/fsm-proto-codegen/proto/fsm-core-async-op-worker/pgfsm/sidecargateway/v1/sidecar_gateway.proto
// — see #100), registers
// a compiled-in actor registry, and serves invoke requests.
//
// Unlike worker-sdk/typescript and worker-sdk/python, this has no
// folder-scanning/dynamic-import step — Go has no runtime mechanism to load
// a function out of a .go source file the way import() (TS) or importlib
// (Python) can (Go plugins exist but require exact toolchain/build-flag
// matching between the plugin and host binary and aren't practical here).
// Instead, ActorWorker takes an explicit []ActorRegistration built at
// compile time by the binary that uses this SDK (see main.go) — the actor
// functions are linked into the binary directly, and "verification"
// happens at compile time (it wouldn't build if the function didn't exist
// or had the wrong signature) rather than at worker startup.
//
// grpc-go's generated client stream (SidecarGatewayService_SessionClient)
// gives a synchronous-looking Send/Recv pair backed by goroutines
// internally — no push-queue needed the way sdk.ts/sdk.py/sdk.rs each build
// one, only a mutex around Send (grpc-go client streams don't allow
// concurrent Send calls; Recv is only ever called from one goroutine here
// too, so it needs no mutex of its own).
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"sync"
	"sync/atomic"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"

	sidecargatewayv1 "github.com/pgfsm/fsm/packages/fsm-proto-codegen/gen/go/sidecargateway/v1"
)

// RegisteredActor is the generated pgfsm.sidecargateway.v1.RegisteredActor
// message, aliased so main.go (which builds these from the compiled actor
// registry) doesn't need to import the generated package itself.
type RegisteredActor = sidecargatewayv1.RegisteredActor

// An actor's compiled-in implementation. A returned error is reported to
// the gateway as an INTERNAL invoke error; a panic is also recovered and
// reported the same way rather than crashing the worker process — the Go
// equivalent of catching a thrown exception in the TypeScript/Python
// versions.
type ActorHandler func(input any) (any, error)

type ActorRegistration struct {
	Meta    RegisteredActor
	Handler ActorHandler
}

type ActorWorkerOptions struct {
	WorkerID          string
	GatewaySocketPath string
	HeartbeatMs       int
}

type ActorWorker struct {
	options    ActorWorkerOptions
	handlers   map[string]ActorHandler
	registered []RegisteredActor
	stopped    atomic.Bool
	conn       *grpc.ClientConn
	stream     sidecargatewayv1.SidecarGatewayService_SessionClient
	sendMu     sync.Mutex
}

func ActorKey(parentFsmName, parentFsmVersion, asyncOperationType, asyncOperationName, asyncOperationVersion, asyncOperationLanguage string) string {
	return fmt.Sprintf("%s@%s@%s@%s@%s@%s", parentFsmName, parentFsmVersion, asyncOperationType, asyncOperationName, asyncOperationVersion, asyncOperationLanguage)
}

func NewActorWorker(options ActorWorkerOptions, registrations []ActorRegistration) *ActorWorker {
	handlers := make(map[string]ActorHandler, len(registrations))
	registered := make([]RegisteredActor, 0, len(registrations))
	for _, reg := range registrations {
		key := ActorKey(reg.Meta.ParentFsmName, reg.Meta.ParentFsmVersion, reg.Meta.AsyncOperationType, reg.Meta.AsyncOperationName, reg.Meta.AsyncOperationVersion, reg.Meta.AsyncOperationLanguage)
		handlers[key] = reg.Handler
		registered = append(registered, reg.Meta)
	}
	return &ActorWorker{options: options, handlers: handlers, registered: registered}
}

func (w *ActorWorker) Run() error {
	if len(w.registered) == 0 {
		return fmt.Errorf("no actors to register, refusing to start worker")
	}

	conn, err := grpc.NewClient("unix://"+w.options.GatewaySocketPath, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return err
	}
	w.conn = conn

	client := sidecargatewayv1.NewSidecarGatewayServiceClient(conn)
	stream, err := client.Session(context.Background())
	if err != nil {
		conn.Close()
		return err
	}
	w.stream = stream

	registeredPtrs := make([]*RegisteredActor, len(w.registered))
	for i := range w.registered {
		registeredPtrs[i] = &w.registered[i]
	}

	if err := w.send(&sidecargatewayv1.SessionRequest{
		Payload: &sidecargatewayv1.SessionRequest_Register{
			Register: &sidecargatewayv1.Register{
				WorkerId:        w.options.WorkerID,
				Language:        "go",
				ProtocolVersion: "1.0",
				Actors:          registeredPtrs,
			},
		},
	}); err != nil {
		conn.Close()
		return err
	}

	first, err := stream.Recv()
	if err != nil {
		conn.Close()
		return err
	}
	ack, ok := first.GetPayload().(*sidecargatewayv1.SessionResponse_RegisterAck)
	if !ok {
		conn.Close()
		return fmt.Errorf("expected register_ack but got %T", first.GetPayload())
	}
	if !ack.RegisterAck.GetAccepted() {
		conn.Close()
		return fmt.Errorf("gateway rejected registration")
	}

	fmt.Printf("Worker %s registered %d actor(s) with the gateway\n", w.options.WorkerID, len(w.registered))

	heartbeatDone := make(chan struct{})
	go func() {
		defer close(heartbeatDone)
		interval := time.Duration(w.options.HeartbeatMs) * time.Millisecond
		for !w.stopped.Load() {
			time.Sleep(interval)
			if w.stopped.Load() {
				return
			}
			err := w.send(&sidecargatewayv1.SessionRequest{
				Payload: &sidecargatewayv1.SessionRequest_Heartbeat{
					Heartbeat: &sidecargatewayv1.Heartbeat{WorkerId: w.options.WorkerID},
				},
			})
			if err != nil {
				w.stopped.Store(true)
				return
			}
		}
	}()

	err = w.serveLoop()
	w.stopped.Store(true)
	<-heartbeatDone
	conn.Close()
	return err
}

func (w *ActorWorker) Stop() {
	if w.stopped.Swap(true) {
		return
	}
	_ = w.send(&sidecargatewayv1.SessionRequest{
		Payload: &sidecargatewayv1.SessionRequest_Unregister{
			Unregister: &sidecargatewayv1.Unregister{WorkerId: w.options.WorkerID},
		},
	})
	if w.conn != nil {
		w.conn.Close()
	}
}

func (w *ActorWorker) send(req *sidecargatewayv1.SessionRequest) error {
	w.sendMu.Lock()
	defer w.sendMu.Unlock()
	return w.stream.Send(req)
}

func (w *ActorWorker) serveLoop() error {
	for !w.stopped.Load() {
		resp, err := w.stream.Recv()
		if err != nil {
			return err
		}

		switch p := resp.GetPayload().(type) {
		case *sidecargatewayv1.SessionResponse_Cancel:
			continue
		case *sidecargatewayv1.SessionResponse_Invoke:
			w.handleInvoke(p.Invoke)
		}
	}
	return nil
}

func (w *ActorWorker) handleInvoke(body *sidecargatewayv1.Invoke) {
	key := ActorKey(body.ParentFsmName, body.ParentFsmVersion, body.AsyncOperationType, body.AsyncOperationName, body.AsyncOperationVersion, body.AsyncOperationLanguage)
	handler, ok := w.handlers[key]
	if !ok {
		w.sendError(body.InvokeId, "NOT_FOUND", fmt.Sprintf("actor not found: %s", key))
		return
	}

	var input any
	if s := body.InputJson; s != "" {
		if err := json.Unmarshal([]byte(s), &input); err != nil {
			w.sendError(body.InvokeId, "INTERNAL", fmt.Sprintf("invalid input_json: %v", err))
			return
		}
	}

	started := time.Now()
	output, err := safeInvoke(handler, input)
	if err != nil {
		w.sendError(body.InvokeId, "INTERNAL", err.Error())
		return
	}

	outputJSON, err := json.Marshal(output)
	if err != nil {
		w.sendError(body.InvokeId, "INTERNAL", err.Error())
		return
	}

	_ = w.send(&sidecargatewayv1.SessionRequest{
		Payload: &sidecargatewayv1.SessionRequest_InvokeResult{
			InvokeResult: &sidecargatewayv1.InvokeResult{
				InvokeId:   body.InvokeId,
				OutputJson: string(outputJSON),
				DurationMs: uint32(time.Since(started).Milliseconds()),
			},
		},
	})
}

func safeInvoke(handler ActorHandler, input any) (output any, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("panic: %v", r)
		}
	}()
	return handler(input)
}

func (w *ActorWorker) sendError(invokeID, code, message string) {
	_ = w.send(&sidecargatewayv1.SessionRequest{
		Payload: &sidecargatewayv1.SessionRequest_InvokeError{
			InvokeError: &sidecargatewayv1.InvokeError{
				InvokeId: invokeID,
				Error: &sidecargatewayv1.InvokeErrorDetail{
					Code:      code,
					Message:   message,
					Retriable: false,
				},
			},
		},
	})
}
