// AUTO-GENERATED from actors-registry.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n<% for (const a of it.actors) { -%>\nfrom .actors.<%~ a.fileBaseName %>.<%~ a.fileBaseName %> import <%~ a.src %>\n<% } -%>\n\nACTOR_REGISTRATIONS = [\n<% for (const a of it.actors) { -%>\n    {\n        "parent_fsm_name": <%~ JSON.stringify(a.parentFsmName) %>,\n        "parent_fsm_version": <%~ JSON.stringify(a.parentFsmVersion) %>,\n        "async_operation_type": <%~ JSON.stringify(a.asyncOperationType) %>,\n        "async_operation_name": <%~ JSON.stringify(a.asyncOperationName) %>,\n        "async_operation_version": <%~ JSON.stringify(a.asyncOperationVersion) %>,\n        "async_operation_language": <%~ JSON.stringify(a.asyncOperationLanguage) %>,\n        "handler": <%~ a.src %>,\n    },\n<% } -%>\n]\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
