// AUTO-GENERATED from actors-registry-aggregate.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n# Each FSM-version\'s registry is imported statically via a dotted path\n# (fsm-compiler-ts validates every FSM-name/version folder name is a valid\n# Python identifier before generating this file, precisely so this can be a\n# plain import instead of a runtime file-path load). The plugin root itself\n# is added to sys.path so each FSM-name folder resolves as a namespace\n# package -- Python has no relative-path import syntax like TS\'s\n# `"../../x/y.ts"` or Rust\'s `#[path]`, so this is the static-import\n# equivalent for a sibling directory.\nimport os\nimport sys\n\n_PLUGIN_ROOT = os.path.abspath(\n    os.path.join(os.path.dirname(os.path.abspath(__file__)), "<%~ it.pluginRootRelPath %>")\n)\nif _PLUGIN_ROOT not in sys.path:\n    sys.path.insert(0, _PLUGIN_ROOT)\n\n<% for (const g of it.groups) { -%>\nfrom <%~ g.key.split("/").join(".") %>.actors.generated_registry import ACTOR_REGISTRATIONS as <%~ g.alias %>\n<% } -%>\n\nACTOR_REGISTRATIONS = [\n<% for (const g of it.groups) { -%>\n    *<%~ g.alias %>,\n<% } -%>\n]\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
