// AUTO-GENERATED from run-async-worker.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '#!/usr/bin/env python3\n# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n"""Python worker for the Activity Gateway: wires this project\'s\ncompiler-generated actor registry into pgfsm-async-worker-sdk\'s\nrun_actor_worker_cli (see pyproject.toml for the pinned version).\n\nUSAGE\n  uv run run_async_worker.py <list|start> [options]\n\nEXAMPLE\n  uv run run_async_worker.py start --gateway-socket /tmp/pgfsm-activity-gateway-workers.sock\n"""\n\nimport logging\nimport sys\n\nfrom pgfsm.async_worker_sdk import run_actor_worker_cli\n\n# Fixed, compiler-generated registry -- see fsm-compiler-ts\'s\n# writeAggregateActorsRegistry. Regenerate with\n# `npx @pgfsm/compiler -c generate-async-logic -f <plugin-root>` after actors\n# change; this import is a build-time coupling to that one app\'s FSM\n# definitions by design (see #84 for why). A plain static import works\n# because this module is always a sibling of run_async_worker.py, which\n# Python puts on sys.path automatically for the running script.\nfrom <%~ it.registryModuleName %> import ACTOR_REGISTRATIONS\n\nif __name__ == "__main__":\n    logging.basicConfig(\n        level=logging.DEBUG if sys.stderr.isatty() else logging.INFO,\n        format="%(asctime)s %(levelname)s %(name)s: %(message)s",\n    )\n    raise SystemExit(run_actor_worker_cli(ACTOR_REGISTRATIONS, sys.argv[1:]))\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
