// AUTO-GENERATED from shared-async-op-registry.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n# Every function-version lives in its own directory tree under this file\'s\n# own directory (sharedAsyncOperation/<version>/actors/<name>/), so this\n# uses the same sys.path-insertion + absolute-dotted-import pattern as the\n# FSM-scoped aggregate registry (see actors-registry-aggregate.eta) rather\n# than a relative import -- Python has no relative-path import syntax for\n# reaching into a sibling subtree the way TS\'s "./x/y.ts" or Rust\'s #[path]\n# can.\nimport os\nimport sys\n\n_SHARED_ASYNC_OP_ROOT = os.path.dirname(os.path.abspath(__file__))\nif _SHARED_ASYNC_OP_ROOT not in sys.path:\n    sys.path.insert(0, _SHARED_ASYNC_OP_ROOT)\n\n<% for (const a of it.actors) { -%>\nfrom <%~ a.importPath %> import <%~ a.src %> as <%~ a.alias %>\n<% } -%>\n\nACTOR_REGISTRATIONS = [\n<% for (const a of it.actors) { -%>\n    {\n        "parent_fsm_name": <%~ JSON.stringify(a.parentFsmName) %>,\n        "parent_fsm_version": <%~ JSON.stringify(a.parentFsmVersion) %>,\n        "async_operation_type": <%~ JSON.stringify(a.asyncOperationType) %>,\n        "async_operation_name": <%~ JSON.stringify(a.asyncOperationName) %>,\n        "async_operation_version": <%~ JSON.stringify(a.asyncOperationVersion) %>,\n        "async_operation_language": <%~ JSON.stringify(a.asyncOperationLanguage) %>,\n        "handler": <%~ a.alias %>,\n    },\n<% } -%>\n]\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
