// AUTO-GENERATED from worker-sdk-pyproject.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n# Python worker for the Activity Gateway. The SDK itself lives in the\n# published pgfsm-async-worker-sdk package; this directory only holds the\n# actors, their compiler-generated registry and run_async_worker.py.\n#\n#   uv run run_async_worker.py list    # print the actors in the registry\n#   uv run run_async_worker.py start   # connect to the gateway and serve\n#\n# Without uv: `python3 -m pip install "pgfsm-async-worker-sdk>=0.1.0,<0.2"`,\n# then `python3 run_async_worker.py start`.\n[project]\nname = "pgfsm-async-worker-python"\nversion = "0.0.0"\nrequires-python = ">=3.10"\ndependencies = [\n  "pgfsm-async-worker-sdk>=0.1.0,<0.2",\n]\n\n[tool.uv]\n# An app, not an installable package: uv only manages its environment.\npackage = false\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
