// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import {
  FSM_DEFINITION as loadtest_v01_definition,
  SYNC_OPERATION_REGISTRATIONS as loadtest_v01,
} from "./loadTest/v01/sync-operation-registry.generated.ts";

export const SYNC_OPERATION_REGISTRATIONS = [
  ...loadtest_v01,
];

export const FSM_DEFINITIONS = [
  loadtest_v01_definition,
];
