// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { helloPgfsm as helloPgfsm_v01 } from "./v01/actors/helloPgfsm/v01/helloPgfsm.ts";
import { helloWorld as helloWorld_v01 } from "./v01/actors/helloWorld/v01/helloWorld.ts";

export type ActorRegistration = {
  parentFsmName: string;
  parentFsmVersion: string;
  asyncOperationType: string;
  asyncOperationName: string;
  asyncOperationVersion: string;
  asyncOperationLanguage: string;
  handler: (input: unknown) => unknown;
};

export const ACTOR_REGISTRATIONS: ActorRegistration[] = [
  {
    parentFsmName: "sharedAsyncOperation",
    parentFsmVersion: "v01",
    asyncOperationType: "sharedAsyncOperation",
    asyncOperationName: "helloPgfsm",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    handler: helloPgfsm_v01,
  },
  {
    parentFsmName: "sharedAsyncOperation",
    parentFsmVersion: "v01",
    asyncOperationType: "sharedAsyncOperation",
    asyncOperationName: "helloWorld",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    handler: helloWorld_v01,
  },
];
