// AUTO-GENERATED from worker-sdk-cargo-toml.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n# Rust worker for the Activity Gateway. The SDK itself lives in the published\n# pgfsm-async-worker-sdk crate; this directory only holds the actors, their\n# compiler-generated registry and src/main.rs.\n#\n#   cargo run --release -- list    # print the actors in the registry\n#   cargo run --release -- start   # connect to the gateway and serve\n[package]\nname = "pgfsm-async-worker-rust"\nversion = "0.0.0"\nedition = "2021"\n# An app, not a library: never published.\npublish = false\n\n[[bin]]\nname = "run-async-worker"\npath = "src/main.rs"\n\n[dependencies]\npgfsm-async-worker-sdk = "0.1"\n# The actor handlers and the generated registry take and return\n# serde_json::Value.\nserde_json = "1"\n# main.rs configures logging once; the SDK only uses the `log` facade.\nenv_logger = "0.11"\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
