// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
package generatedregistry

import (
	loadtest_v01_loadwork "e2e/loadtest/v01/go/actors/loadwork"
)

type ActorRegistration struct {
	ParentFsmName          string
	ParentFsmVersion       string
	AsyncOperationType     string
	AsyncOperationName     string
	AsyncOperationVersion  string
	AsyncOperationLanguage string
	// MaxConcurrency is the actor's own limit, from its stub's MaxConcurrency;
	// 0 falls back to the worker's --max-concurrency.
	MaxConcurrency uint32
	Handler        func(input any) (any, error)
}

func ActorRegistrations() []ActorRegistration {
	return []ActorRegistration{
		{
			ParentFsmName:          "loadTest",
			ParentFsmVersion:       "v01",
			AsyncOperationType:     "internalAsyncOperation",
			AsyncOperationName:     "loadWork",
			AsyncOperationVersion:  "v01",
			AsyncOperationLanguage: "go",
			MaxConcurrency:         uint32(loadtest_v01_loadwork.MaxConcurrency),
			Handler:                loadtest_v01_loadwork.LoadWork,
		},
	}
}
