# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
from .actors.loadWork.loadWork import loadWork, MAX_CONCURRENCY as _max_concurrency_loadWork

ACTOR_REGISTRATIONS = [
    {
        "parent_fsm_name": "loadTest",
        "parent_fsm_version": "v01",
        "async_operation_type": "internalAsyncOperation",
        "async_operation_name": "loadWork",
        "async_operation_version": "v01",
        "async_operation_language": "python",
        "max_concurrency": _max_concurrency_loadWork,
        "handler": loadWork,
    },
]
