// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
#[path = "actors/byeFromPgfsm/byeFromPgfsm.rs"]
#[allow(non_snake_case)]
mod byeFromPgfsm_v01;
#[path = "actors/helloFromPgfsm/helloFromPgfsm.rs"]
#[allow(non_snake_case)]
mod helloFromPgfsm_v01;

pub struct ActorRegistration {
    pub parent_fsm_name: &'static str,
    pub parent_fsm_version: &'static str,
    pub async_operation_type: &'static str,
    pub async_operation_name: &'static str,
    pub async_operation_version: &'static str,
    pub async_operation_language: &'static str,
    pub handler: fn(serde_json::Value) -> serde_json::Value,
}

pub fn actor_registrations() -> Vec<ActorRegistration> {
    vec![
        ActorRegistration {
            parent_fsm_name: "sharedAsyncOperation",
            parent_fsm_version: "v01",
            async_operation_type: "sharedAsyncOperation",
            async_operation_name: "byeFromPgfsm",
            async_operation_version: "v01",
            async_operation_language: "rust",
            handler: byeFromPgfsm_v01::byeFromPgfsm,
        },
        ActorRegistration {
            parent_fsm_name: "sharedAsyncOperation",
            parent_fsm_version: "v01",
            async_operation_type: "sharedAsyncOperation",
            async_operation_name: "helloFromPgfsm",
            async_operation_version: "v01",
            async_operation_language: "rust",
            handler: helloFromPgfsm_v01::helloFromPgfsm,
        },
    ]
}
