// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import {
  assignBattery,
  assignCoolantLevel,
  assignOilPressure,
  assignTirePressure,
} from "./actions/index.ts";

export type SyncOperationRegistration = {
  fsmName: string;
  fsmVersion: string;
  syncOperationType: "action" | "guard" | "delay";
  syncOperationName: string;
  syncOperationLanguage: string;
  handler: (...args: unknown[]) => unknown;
};

export type FsmDefinitionDigest = {
  fsmName: string;
  fsmVersion: string;
  fsmJsonSha256: string;
};

// Canonical (RFC 8785) SHA-256 of the fsm.json this registry was generated
// from; the fsmlet refuses to start if the loaded definition differs.
export const FSM_DEFINITION: FsmDefinitionDigest = {
  fsmName: "vitalsWorkflow",
  fsmVersion: "v01",
  fsmJsonSha256:
    "69997c288cce788cc95050152d359fa6707d0df005a5bb6d7f5a957c5ffcea1f",
};

export const SYNC_OPERATION_REGISTRATIONS: SyncOperationRegistration[] = [
  {
    fsmName: "vitalsWorkflow",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignTirePressure",
    syncOperationLanguage: "typescript",
    handler: assignTirePressure,
  },
  {
    fsmName: "vitalsWorkflow",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignOilPressure",
    syncOperationLanguage: "typescript",
    handler: assignOilPressure,
  },
  {
    fsmName: "vitalsWorkflow",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignCoolantLevel",
    syncOperationLanguage: "typescript",
    handler: assignCoolantLevel,
  },
  {
    fsmName: "vitalsWorkflow",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignBattery",
    syncOperationLanguage: "typescript",
    handler: assignBattery,
  },
];
