// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { delay1000 } from "./delays/index.ts";

export type SyncOperationRegistration = {
  fsmName: string;
  fsmVersion: string;
  syncOperationType: "action" | "guard" | "delay";
  syncOperationName: string;
  syncOperationLanguage: string;
  handler: (...args: unknown[]) => unknown;
};

export const SYNC_OPERATION_REGISTRATIONS: SyncOperationRegistration[] = [
  {
    fsmName: "carVitals",
    fsmVersion: "v01",
    syncOperationType: "delay",
    syncOperationName: "1000",
    syncOperationLanguage: "typescript",
    handler: delay1000,
  },
];
