// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { delay1000 } from "./delays/1000/1000.ts";

export type SyncOperationRegistration = {
  fsmName: string;
  fsmVersion: string;
  syncOperationType: "action" | "guard" | "delay";
  syncOperationName: string;
  syncOperationLanguage: string;
  handler: (...args: unknown[]) => unknown;
};

export type FsmDefinitionDigest = {
  fsmName: string;
  fsmVersion: string;
  fsmJsonSha256: string;
};

// Canonical (RFC 8785) SHA-256 of the fsm.json this registry was generated
// from; the fsmlet refuses to start if the loaded definition differs.
export const FSM_DEFINITION: FsmDefinitionDigest = {
  fsmName: "carVitals",
  fsmVersion: "v01",
  fsmJsonSha256:
    "3b53b880bfc65d3f97375a1116ec0cbdfdeff1fb9902d88f2bfed6962ea63153",
};

export const SYNC_OPERATION_REGISTRATIONS: SyncOperationRegistration[] = [
  {
    fsmName: "carVitals",
    fsmVersion: "v01",
    syncOperationType: "delay",
    syncOperationName: "1000",
    syncOperationLanguage: "typescript",
    handler: delay1000,
  },
];
