#!/usr/bin/env python3
# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
"""worker-sdk/python cli — Python reference worker for the Activity Gateway.

Python counterpart of ../typescript/cli.ts: loads actors from a
compiler-generated registry (a fixed, known file — see fsm-compiler-ts's
writeAggregateActorsRegistry) instead of scanning a folder path, and hands
that list straight to sdk.ActorWorker.

USAGE
  python3 cli.py <list|start> [options]

EXAMPLE
  python3 cli.py start --gateway-socket /tmp/pgfsm-activity-gateway-workers.sock
"""

from __future__ import annotations

import argparse
import signal
import sys
import uuid

from sdk import ActorWorker

# Fixed, compiler-generated registry -- see fsm-compiler-ts's
# writeAggregateActorsRegistry. Regenerate with
# `deno task cli -c generate-async-logic -f <plugin-root>` after actors
# change; this import is a build-time coupling to that one app's FSM
# definitions by design (see #84 for why). A plain static import works
# because this module is always a sibling of cli.py, which Python puts on
# sys.path automatically for the running script.
from python_actors_registry_generated import ACTOR_REGISTRATIONS

DEFAULT_GATEWAY_SOCKET = "/tmp/pgfsm-activity-gateway-workers.sock"
DEFAULT_HEARTBEAT_MS = 5000


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="worker-sdk/python cli — reference worker for the Activity Gateway"
    )
    parser.add_argument("command", choices=["list", "start"])
    parser.add_argument(
        "-g",
        "--gateway-socket",
        default=DEFAULT_GATEWAY_SOCKET,
        help=f"Sidecar socket to connect to (default: {DEFAULT_GATEWAY_SOCKET})",
    )
    parser.add_argument(
        "-i",
        "--worker-id",
        default=None,
        help="Stable worker identity (default: python-<random>)",
    )
    parser.add_argument(
        "--heartbeat-ms",
        type=int,
        default=DEFAULT_HEARTBEAT_MS,
        help=f"Heartbeat interval (default: {DEFAULT_HEARTBEAT_MS})",
    )
    return parser


def main(argv: list[str]) -> int:
    args = build_parser().parse_args(argv)

    worker_id = args.worker_id or f"python-{uuid.uuid4().hex[:8]}"
    registrations = ACTOR_REGISTRATIONS

    print(f"{len(registrations)} actor(s) compiled into this registry")
    for reg in registrations:
        print(
            f"  + {reg['async_operation_name']}@{reg['async_operation_version']} "
            f"(parent {reg['parent_fsm_name']}@{reg['parent_fsm_version']})"
        )

    if args.command == "list":
        return 0

    if not registrations:
        print("No actors in the registry, refusing to start worker", file=sys.stderr)
        return 1

    worker = ActorWorker(
        worker_id=worker_id,
        gateway_socket_path=args.gateway_socket,
        registrations=registrations,
        heartbeat_ms=args.heartbeat_ms,
    )

    def _on_signal(signum: int, frame: object) -> None:
        del signum, frame
        print("Shutdown requested — stopping worker...")
        worker.stop()

    signal.signal(signal.SIGINT, _on_signal)
    signal.signal(signal.SIGTERM, _on_signal)

    print(f"Starting worker {worker_id}: gateway-socket={args.gateway_socket}")
    try:
        worker.run()
    except Exception as exc:  # noqa: BLE001 — reported and turned into an exit code
        print(f"Worker {worker_id} failed: {exc}", file=sys.stderr)
        return 1

    print(f"Worker {worker_id} stopped.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
