// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { parseArgs } from "@std/cli/parse-args";
import { getLogger } from "@logtape/logtape";
import { CATEGORY, configureLogging, isTerminal } from "@pgfsm/logging";
import { ActorWorker } from "./sdk.ts";
// Fixed, compiler-generated registry -- see fsm-compiler-ts's
// writeAggregateActorsRegistry. Regenerate with
// `deno task cli -c generate-async-logic -f <plugin-root>` after actors
// change; this import path is a build-time coupling to that one app's
// FSM definitions by design (see #84 for why).
import { ACTOR_REGISTRATIONS } from "./typescript-actors-registry.generated.ts";

const logger = getLogger([
  "@pgfsm/worker",
  "async-op-worker-gateway",
  "worker-sdk-ts",
  "cli",
]);
await configureLogging({
  levels: { [CATEGORY.worker]: isTerminal ? "debug" : "info" },
});

function printHelp(): void {
  logger.info(`
worker-sdk/typescript cli — TypeScript reference worker for the Activity Gateway

USAGE
  deno run --allow-all cli.ts <list|start> [options]

OPTIONS
  -g, --gateway-socket <path>   Sidecar socket to connect to (default: /tmp/pgfsm-activity-gateway-workers.sock)
  -i, --worker-id <id>          Stable worker identity (default: typescript-<random>)
      --heartbeat-ms <ms>       Heartbeat interval (default: 5000)
  -h, --help                    Show this help message

COMMANDS
  list    Print the actors compiled into this binary's registry, without connecting to the gateway.
  start   Connect to the gateway and serve invocations for every actor in the registry until stopped.

DESCRIPTION
  Actors come from a compiler-generated registry (see
  fsm-compiler-ts's writeAggregateActorsRegistry) -- statically imported at
  build time, not scanned or dynamically loaded at startup.

EXAMPLE
  deno run --allow-all cli.ts start --gateway-socket /tmp/pgfsm-activity-gateway-workers.sock
`);
}

const args = parseArgs(Deno.args, {
  string: ["gateway-socket", "worker-id", "heartbeat-ms"],
  boolean: ["help"],
  alias: {
    h: "help",
    g: "gateway-socket",
    i: "worker-id",
  },
});

if (args.help) {
  printHelp();
  Deno.exit(0);
}

const command = String(args._[0] ?? "");
if (command !== "list" && command !== "start") {
  logger.error("First argument must be one of: list, start. Got: {command}", {
    command: command || "(none)",
  });
  printHelp();
  Deno.exit(1);
}

const gatewaySocketPath = args["gateway-socket"] ??
  "/tmp/pgfsm-activity-gateway-workers.sock";
const workerId = args["worker-id"] ??
  `typescript-${crypto.randomUUID().slice(0, 8)}`;
const heartbeatMs = args["heartbeat-ms"]
  ? Number(args["heartbeat-ms"])
  : undefined;

logger.info("{count} actor(s) compiled into this registry", {
  count: ACTOR_REGISTRATIONS.length,
});
for (const reg of ACTOR_REGISTRATIONS) {
  logger.info(
    "  + {asyncOperationName}@{asyncOperationVersion} (parent {parentFsmName}@{parentFsmVersion})",
    {
      asyncOperationName: reg.asyncOperationName,
      asyncOperationVersion: reg.asyncOperationVersion,
      parentFsmName: reg.parentFsmName,
      parentFsmVersion: reg.parentFsmVersion,
    },
  );
}

if (command === "list") {
  Deno.exit(0);
}

if (ACTOR_REGISTRATIONS.length === 0) {
  logger.error("No actors in the registry, refusing to start worker");
  Deno.exit(1);
}

const worker = new ActorWorker(
  { workerId, language: "typescript", gatewaySocketPath, heartbeatMs },
  ACTOR_REGISTRATIONS,
);

const onSignal = () => {
  logger.info("Shutdown requested — stopping worker...");
  worker.stop();
};
Deno.addSignalListener("SIGINT", onSignal);
Deno.addSignalListener("SIGTERM", onSignal);

try {
  logger.info(
    "Starting worker {workerId}: gateway-socket={socket}",
    { workerId, socket: gatewaySocketPath },
  );
  await worker.run();
  logger.info("Worker {workerId} stopped.", { workerId });
} catch (err) {
  const msg = err instanceof Error ? (err.stack ?? err.message) : String(err);
  logger.error("Worker {workerId} failed: {error}", { workerId, error: msg });
  Deno.exit(1);
}
