// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { CATEGORY, configureLogging, isTerminal } from "@pgfsm/logging";
import { runActorWorkerCli } from "@pgfsm/async-worker-sdk";
// Fixed, compiler-generated registry -- see fsm-compiler-ts's
// writeAggregateActorsRegistry. Regenerate with
// `npx @pgfsm/compiler -c generate-async-logic -f <plugin-root>` after actors
// change; this import path is a build-time coupling to that one app's
// FSM definitions by design (see #84 for why).
import { ACTOR_REGISTRATIONS } from "./typescript-actors-registry.generated.ts";

await configureLogging({
  levels: { [CATEGORY.worker]: isTerminal ? "debug" : "info" },
});

Deno.exit(
  await runActorWorkerCli({
    registrations: ACTOR_REGISTRATIONS,
    args: Deno.args,
  }),
);
