# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
# Each FSM-version's registry is imported statically via a dotted path
# (fsm-compiler-ts validates every FSM-name/version folder name is a valid
# Python identifier before generating this file, precisely so this can be a
# plain import instead of a runtime file-path load). The plugin root itself
# is added to sys.path so each FSM-name folder resolves as a namespace
# package -- Python has no relative-path import syntax like TS's
# `"../../x/y.ts"` or Rust's `#[path]`, so this is the static-import
# equivalent for a sibling directory two levels up.
import os
import sys

_PLUGIN_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../fsm")
)
if _PLUGIN_ROOT not in sys.path:
    sys.path.insert(0, _PLUGIN_ROOT)

from creditCheck.v01.python.actors.generated_registry import ACTOR_REGISTRATIONS as creditcheck_v01

ACTOR_REGISTRATIONS = [
    *creditcheck_v01,
]
