// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
//! worker-sdk/rust reference binary — Rust reference worker for the
//! Activity Gateway.
//!
//! Rust counterpart of ../typescript/cli.ts and ../python/cli.py: actors
//! come from a compiler-generated registry (`generated_registry` below,
//! `#[path]`-included from a fixed location — see fsm-compiler-ts's
//! `writeAggregateActorsRegistry`), not a folder scan. Rust has no runtime
//! mechanism to load a function out of a `.rs` source file the way
//! `import()` (TS) or `importlib` (Python) can, so the registry's handlers
//! are plain `fn` pointers linked into this binary at compile time —
//! "verification" happens at compile time (it wouldn't build if a function
//! didn't exist or had the wrong signature), not at worker startup.
//!
//! USAGE
//!   cargo run --release -- [options]
//!
//! OPTIONS
//!   --gateway-socket <path>   Sidecar socket to connect to (default: /tmp/pgfsm-activity-gateway-workers.sock)
//!   --worker-id <id>          Stable worker identity (default: rust-<pid>)
//!   --heartbeat-ms <ms>       Heartbeat interval (default: 5000)
//!   -h, --help                Show this help message

mod sdk;

// Fixed, compiler-generated registry -- see fsm-compiler-ts's
// writeAggregateActorsRegistry. Regenerate with
// `deno task cli -c generate-async-logic -f <plugin-root>` after actors
// change; this path is a build-time coupling to that one app's FSM
// definitions by design (see #84 for why). Nested `#[path]` declarations
// inside the included file resolve relative to *that file's* own directory,
// not this one, so its own `#[path = "fsm/..."]` mods still work correctly.
#[path = "../rust-actors-registry.generated.rs"]
mod generated_registry;

use pgfsm_proto_codegen::pgfsm::sidecargateway::v1::RegisteredActor;
use sdk::{ActorHandler, ActorRegistration, ActorWorker, ActorWorkerOptions};
use std::env;
use std::process;
use std::sync::Arc;

struct Args {
    gateway_socket_path: String,
    worker_id: String,
    heartbeat_ms: u64,
}

fn print_help() {
    println!(
        "worker-sdk-rust — Rust reference worker for the Activity Gateway\n\n\
USAGE\n  cargo run --release -- [options]\n\n\
OPTIONS\n\
  --gateway-socket <path>   Sidecar socket to connect to (default: /tmp/pgfsm-activity-gateway-workers.sock)\n\
  --worker-id <id>          Stable worker identity (default: rust-<pid>)\n\
  --heartbeat-ms <ms>       Heartbeat interval (default: 5000)\n\
  -h, --help                Show this help message"
    );
}

fn parse_args() -> Args {
    let mut gateway_socket_path = "/tmp/pgfsm-activity-gateway-workers.sock".to_string();
    let mut worker_id: Option<String> = None;
    let mut heartbeat_ms: u64 = 5000;

    let mut args = env::args().skip(1);
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "-h" | "--help" => {
                print_help();
                process::exit(0);
            }
            "--gateway-socket" => {
                gateway_socket_path = args.next().unwrap_or_else(|| {
                    eprintln!("--gateway-socket requires a value");
                    process::exit(1);
                });
            }
            "--worker-id" => {
                worker_id = Some(args.next().unwrap_or_else(|| {
                    eprintln!("--worker-id requires a value");
                    process::exit(1);
                }));
            }
            "--heartbeat-ms" => {
                let value = args.next().unwrap_or_else(|| {
                    eprintln!("--heartbeat-ms requires a value");
                    process::exit(1);
                });
                heartbeat_ms = value.parse().unwrap_or_else(|_| {
                    eprintln!("--heartbeat-ms must be a positive integer, got: {}", value);
                    process::exit(1);
                });
            }
            other => {
                eprintln!("Unknown argument: {}", other);
                print_help();
                process::exit(1);
            }
        }
    }

    let worker_id = worker_id.unwrap_or_else(|| format!("rust-{}", process::id()));

    Args {
        gateway_socket_path,
        worker_id,
        heartbeat_ms,
    }
}

fn registrations_from_generated() -> Vec<ActorRegistration> {
    generated_registry::actor_registrations()
        .into_iter()
        .map(|reg| ActorRegistration {
            meta: RegisteredActor {
                parent_fsm_name: reg.parent_fsm_name.to_string(),
                parent_fsm_version: reg.parent_fsm_version.to_string(),
                async_operation_type: reg.async_operation_type.to_string(),
                async_operation_name: reg.async_operation_name.to_string(),
                async_operation_version: reg.async_operation_version.to_string(),
                async_operation_language: reg.async_operation_language.to_string(),
                ..Default::default()
            },
            handler: Box::new(reg.handler) as ActorHandler,
        })
        .collect()
}

#[tokio::main]
async fn main() {
    let args = parse_args();

    let registrations = registrations_from_generated();
    println!(
        "{} actor(s) compiled into this registry",
        registrations.len()
    );
    for reg in &registrations {
        println!(
            "  + {}@{} (parent {}@{})",
            reg.meta.async_operation_name,
            reg.meta.async_operation_version,
            reg.meta.parent_fsm_name,
            reg.meta.parent_fsm_version
        );
    }

    if registrations.is_empty() {
        eprintln!("No actors in the registry, refusing to start worker");
        process::exit(1);
    }

    let worker = Arc::new(ActorWorker::new(
        ActorWorkerOptions {
            worker_id: args.worker_id.clone(),
            gateway_socket_path: args.gateway_socket_path.clone(),
            heartbeat_ms: args.heartbeat_ms,
        },
        registrations,
    ));

    let worker_for_signal = worker.clone();
    ctrlc::set_handler(move || {
        println!("Shutdown requested — stopping worker...");
        worker_for_signal.stop();
    })
    .expect("failed to set SIGINT/SIGTERM handler");

    println!(
        "Starting worker {}: gateway-socket={}",
        args.worker_id, args.gateway_socket_path
    );

    if let Err(err) = worker.run().await {
        eprintln!("Worker {} failed: {}", args.worker_id, err);
        process::exit(1);
    }

    println!("Worker {} stopped.", args.worker_id);
}
