// AUTO-GENERATED from actors-registry-aggregate.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n<% for (const g of it.groups) { -%>\nimport { ACTOR_REGISTRATIONS as <%~ g.alias %> } from "<%~ g.relDir %>/typescript/actors/generated-registry.ts";\n<% } -%>\n\nexport const ACTOR_REGISTRATIONS = [\n<% for (const g of it.groups) { -%>\n  ...<%~ g.alias %>,\n<% } -%>\n];\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
