// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import dotenv from "dotenv";
import { getLogger } from "@logtape/logtape";
import { CATEGORY, configureLogging, isTerminal } from "@pgfsm/logging";
import { SYNC_OPERATION_REGISTRATIONS } from "./aggregate-generated-sync-operation-registry.ts";
import { runFsmlet } from "@pgfsm/sync-worker";

dotenv.config({ path: ".env" });

const level = isTerminal ? "debug" : "info";
await configureLogging({
  levels: {
    [CATEGORY.worker]: level,
    [CATEGORY.fsmlet]: level,
    [CATEGORY.db]: level,
  },
});

const logger = getLogger([CATEGORY.fsmlet]);

const controller = new AbortController();
let shutdownRequested = false;

const onSignal = () => {
  if (shutdownRequested) {
    logger.info("Force exit.");
    Deno.exit(0);
  }
  shutdownRequested = true;
  logger.info(
    "Shutdown requested — stopping gracefully. Ctrl+C again to force exit...",
  );
  controller.abort();
};

Deno.addSignalListener("SIGINT", onSignal);
Deno.addSignalListener("SIGTERM", onSignal);

await runFsmlet(
  { connectionString: Deno.env.get("DATABASE_URL") ?? "" },
  SYNC_OPERATION_REGISTRATIONS,
  { signal: controller.signal },
);
