// AUTO-GENERATED from run-async-worker.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\nimport { CATEGORY, configureLogging, isTerminal } from "@pgfsm/logging";\nimport { runActorWorkerCli } from "@pgfsm/async-worker-sdk";\n// Fixed, compiler-generated registry -- see fsm-compiler-ts\'s\n// writeAggregateActorsRegistry. Regenerate with\n// `npx @pgfsm/compiler -c generate-async-logic -f <plugin-root>` after actors\n// change; this import path is a build-time coupling to that one app\'s\n// FSM definitions by design (see #84 for why).\nimport { ACTOR_REGISTRATIONS } from "<%~ it.registryImportPath %>";\n\nawait configureLogging({\n  levels: { [CATEGORY.worker]: isTerminal ? "debug" : "info" },\n});\n\nDeno.exit(\n  await runActorWorkerCli({\n    registrations: ACTOR_REGISTRATIONS,\n    args: Deno.args,\n  }),\n);\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
