// AUTO-GENERATED from run-sync-worker.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\nimport { SYNC_OPERATION_REGISTRATIONS } from "./aggregate-generated-sync-operation-registry.ts";\nimport { runFsmlet } from "@pgfsm/sync-worker";\n\nawait runFsmlet(\n  { connectionString: Deno.env.get("DATABASE_URL") ?? "" },\n  SYNC_OPERATION_REGISTRATIONS,\n);\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
