// AUTO-GENERATED from shared-async-op-registry.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n<% for (const a of it.actors) { -%>\nimport { <%~ a.src %> as <%~ a.alias %> } from "<%~ a.importPath %>";\n<% } -%>\n\nexport type ActorRegistration = {\n  parentFsmName: string;\n  parentFsmVersion: string;\n  asyncOperationType: string;\n  asyncOperationName: string;\n  asyncOperationVersion: string;\n  asyncOperationLanguage: string;\n  handler: (input: unknown) => unknown;\n};\n\nexport const ACTOR_REGISTRATIONS: ActorRegistration[] = [\n<% for (const a of it.actors) { -%>\n  {\n    parentFsmName: <%~ JSON.stringify(a.parentFsmName) %>,\n    parentFsmVersion: <%~ JSON.stringify(a.parentFsmVersion) %>,\n    asyncOperationType: <%~ JSON.stringify(a.asyncOperationType) %>,\n    asyncOperationName: <%~ JSON.stringify(a.asyncOperationName) %>,\n    asyncOperationVersion: <%~ JSON.stringify(a.asyncOperationVersion) %>,\n    asyncOperationLanguage: <%~ JSON.stringify(a.asyncOperationLanguage) %>,\n    handler: <%~ a.alias %>,\n  },\n<% } -%>\n];\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
