// AUTO-GENERATED from sync-operation-registry.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n<% for (const g of it.groups) { -%>\n<% if (g.entries.length > 0) { -%>\nimport { <%~ g.entries.map((e) => e.importName).join(", ") %> } from "./<%~ g.moduleFile %>/index.ts";\n<% } -%>\n<% } -%>\n\nexport type SyncOperationRegistration = {\n  fsmName: string;\n  fsmVersion: string;\n  syncOperationType: "action" | "guard" | "delay";\n  syncOperationName: string;\n  syncOperationLanguage: string;\n  handler: (...args: unknown[]) => unknown;\n};\n\nexport const SYNC_OPERATION_REGISTRATIONS: SyncOperationRegistration[] = [\n<% for (const g of it.groups) { -%>\n<% for (const e of g.entries) { -%>\n  {\n    fsmName: <%~ JSON.stringify(it.fsmName) %>,\n    fsmVersion: <%~ JSON.stringify(it.fsmVersion) %>,\n    syncOperationType: <%~ JSON.stringify(g.kind) %>,\n    syncOperationName: <%~ JSON.stringify(e.name) %>,\n    syncOperationLanguage: <%~ JSON.stringify(it.lang) %>,\n    handler: <%~ e.importName %>,\n  },\n<% } -%>\n<% } -%>\n];\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
