// AUTO-GENERATED from sync-worker-deno-json.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '{\n  "name": <%~ JSON.stringify(it.name) %>,\n  "description": "Generated by @pgfsm/compiler. Runs this project\'s FSM sync-operation worker via @pgfsm/sync-worker.",\n  "exports": "./run-sync-worker.ts",\n  "imports": {\n    "@pgfsm/sync-worker": "npm:@pgfsm/sync-worker@^0.2.0"\n  },\n  "tasks": {\n    "dev": "deno run --allow-all run-sync-worker.ts",\n    "dev:watch": "deno run --allow-all --watch=. run-sync-worker.ts"\n  }\n}\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
