// AUTO-GENERATED from worker-sdk-deno-json.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '{\n  "description": "Generated by @pgfsm/compiler. Runs this project\'s async-operation actors via @pgfsm/async-worker-sdk.",\n  "imports": {\n    "@pgfsm/async-worker-sdk": "npm:@pgfsm/async-worker-sdk@^0.1.0",\n    "@pgfsm/logging": "npm:@pgfsm/logging@^0.1.0"\n  },\n  "tasks": {\n    "list": "deno run --allow-all run-async-worker.ts list",\n    "start": "deno run --allow-all run-async-worker.ts start"\n  }\n}\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
