// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { assignError, assignTasks } from "./actions/index.ts";

export type SyncOperationRegistration = {
  fsmName: string;
  fsmVersion: string;
  syncOperationType: "action" | "guard" | "delay";
  syncOperationName: string;
  syncOperationLanguage: string;
  handler: (...args: unknown[]) => unknown;
};

export const SYNC_OPERATION_REGISTRATIONS: SyncOperationRegistration[] = [
  {
    fsmName: "taskMachineConfig",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignTasks",
    syncOperationLanguage: "typescript",
    handler: assignTasks,
  },
  {
    fsmName: "taskMachineConfig",
    fsmVersion: "v01",
    syncOperationType: "action",
    syncOperationName: "assignError",
    syncOperationLanguage: "typescript",
    handler: assignError,
  },
];
