// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import {
  assignBattery,
  assignCoolantLevel,
  assignOilPressure,
  assignTirePressure,
} from "./actions/index.ts";

export type SyncOperationRegistration = {
  fsmName: string;
  fsmVersion: string;
  syncOperationType: "action" | "guard" | "delay";
  syncOperationName: string;
  syncOperationLanguage: string;
  handler: (...args: unknown[]) => unknown;
};

export const SYNC_OPERATION_REGISTRATIONS: SyncOperationRegistration[] = [
  {
    fsmName: "vitalsWorkflow",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "assignTirePressure",
    syncOperationLanguage: "typescript",
    handler: assignTirePressure,
  },
  {
    fsmName: "vitalsWorkflow",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "assignOilPressure",
    syncOperationLanguage: "typescript",
    handler: assignOilPressure,
  },
  {
    fsmName: "vitalsWorkflow",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "assignCoolantLevel",
    syncOperationLanguage: "typescript",
    handler: assignCoolantLevel,
  },
  {
    fsmName: "vitalsWorkflow",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "assignBattery",
    syncOperationLanguage: "typescript",
    handler: assignBattery,
  },
];
