// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
#[path = "./loadTest/v01/actors/mod.rs"]
mod loadtest_v01;

pub struct ActorRegistration {
    pub parent_fsm_name: &'static str,
    pub parent_fsm_version: &'static str,
    pub async_operation_type: &'static str,
    pub async_operation_name: &'static str,
    pub async_operation_version: &'static str,
    pub async_operation_language: &'static str,
    /// The actor's own limit, from its stub's `MAX_CONCURRENCY`; 0 falls back
    /// to the worker's --max-concurrency. Unread by a main.rs from before #435.
    #[allow(dead_code)]
    pub max_concurrency: u32,
    pub handler: fn(serde_json::Value) -> serde_json::Value,
}

pub fn actor_registrations() -> Vec<ActorRegistration> {
    vec![ActorRegistration {
        parent_fsm_name: "loadTest",
        parent_fsm_version: "v01",
        async_operation_type: "internalAsyncOperation",
        async_operation_name: "loadWork",
        async_operation_version: "v01",
        async_operation_language: "rust",
        max_concurrency: loadtest_v01::loadWork::MAX_CONCURRENCY as u32,
        handler: loadtest_v01::loadWork,
    }]
}
