# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
# Every function-version lives in its own directory tree under this file's
# own directory (sharedAsyncOperation/<version>/actors/<name>/), so this
# uses the same sys.path-insertion + absolute-dotted-import pattern as the
# FSM-scoped aggregate registry (see actors-registry-aggregate.eta) rather
# than a relative import -- Python has no relative-path import syntax for
# reaching into a sibling subtree the way TS's "./x/y.ts" or Rust's #[path]
# can.
import os
import sys

_SHARED_ASYNC_OP_ROOT = os.path.dirname(os.path.abspath(__file__))
if _SHARED_ASYNC_OP_ROOT not in sys.path:
    sys.path.insert(0, _SHARED_ASYNC_OP_ROOT)

from v01.actors.byeFromPgfsm.byeFromPgfsm import byeFromPgfsm as byeFromPgfsm_v01
from v01.actors.helloFromPgfsm.helloFromPgfsm import helloFromPgfsm as helloFromPgfsm_v01

ACTOR_REGISTRATIONS = [
    {
        "parent_fsm_name": "sharedAsyncOperation",
        "parent_fsm_version": "v01",
        "async_operation_type": "sharedAsyncOperation",
        "async_operation_name": "byeFromPgfsm",
        "async_operation_version": "v01",
        "async_operation_language": "python",
        "handler": byeFromPgfsm_v01,
    },
    {
        "parent_fsm_name": "sharedAsyncOperation",
        "parent_fsm_version": "v01",
        "async_operation_type": "sharedAsyncOperation",
        "async_operation_name": "helloFromPgfsm",
        "async_operation_version": "v01",
        "async_operation_language": "python",
        "handler": helloFromPgfsm_v01,
    },
]
