// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { ACTOR_REGISTRATIONS as creditcheck_v01 } from "../../fsm/creditCheck/v01/typescript/actors/generated-registry.ts";
import { ACTOR_REGISTRATIONS as creditcheck_v02 } from "../../fsm/creditCheck/v02/typescript/actors/generated-registry.ts";
import { ACTOR_REGISTRATIONS as vitalsworkflow_v01 } from "../../fsm/vitalsWorkflow/v01/typescript/actors/generated-registry.ts";
import { ACTOR_REGISTRATIONS as vitalsworkflow_v02 } from "../../fsm/vitalsWorkflow/v02/typescript/actors/generated-registry.ts";
import { ACTOR_REGISTRATIONS as taskmachineconfig_v01 } from "../../fsm/taskMachineConfig/v01/typescript/actors/generated-registry.ts";
import { ACTOR_REGISTRATIONS as taskmachineconfig_v02 } from "../../fsm/taskMachineConfig/v02/typescript/actors/generated-registry.ts";

export const ACTOR_REGISTRATIONS = [
  ...creditcheck_v01,
  ...creditcheck_v02,
  ...vitalsworkflow_v01,
  ...vitalsworkflow_v02,
  ...taskmachineconfig_v01,
  ...taskmachineconfig_v02,
];
