// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
#[path = "mod.rs"]
mod actors;

pub struct ActorRegistration {
    pub parent_fsm_name: &'static str,
    pub parent_fsm_version: &'static str,
    pub async_operation_type: &'static str,
    pub async_operation_name: &'static str,
    pub async_operation_version: &'static str,
    pub async_operation_language: &'static str,
    pub handler: fn(serde_json::Value) -> serde_json::Value,
}

pub fn actor_registrations() -> Vec<ActorRegistration> {
    vec![ActorRegistration {
        parent_fsm_name: "creditCheck",
        parent_fsm_version: "v01",
        async_operation_type: "internalAsyncOperation",
        async_operation_name: "checkBureauRust",
        async_operation_version: "v01",
        async_operation_language: "rust",
        handler: actors::checkBureauRust,
    }]
}
