// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { assignTirePressure } from "./actions/assignTirePressure/assignTirePressure.ts";
import { assignOilPressure } from "./actions/assignOilPressure/assignOilPressure.ts";
import { assignCoolantLevel } from "./actions/assignCoolantLevel/assignCoolantLevel.ts";
import { assignBattery } from "./actions/assignBattery/assignBattery.ts";

export type SyncOperationRegistration = {
  fsmName: string;
  fsmVersion: string;
  syncOperationType: "action" | "guard" | "delay";
  syncOperationName: string;
  syncOperationLanguage: string;
  handler: (...args: unknown[]) => unknown;
};

export type FsmDefinitionDigest = {
  fsmName: string;
  fsmVersion: string;
  fsmJsonSha256: string;
};

// Canonical (RFC 8785) SHA-256 of the fsm.json this registry was generated
// from; the fsmlet refuses to start if the loaded definition differs.
export const FSM_DEFINITION: FsmDefinitionDigest = {
  fsmName: "vitalsWorkflow",
  fsmVersion: "v02",
  fsmJsonSha256:
    "4fc44694a06c523f1c5ece495226b6585f1f0cf310ce7514e4decc07cbd7c4fe",
};

export const SYNC_OPERATION_REGISTRATIONS: SyncOperationRegistration[] = [
  {
    fsmName: "vitalsWorkflow",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "assignTirePressure",
    syncOperationLanguage: "typescript",
    handler: assignTirePressure,
  },
  {
    fsmName: "vitalsWorkflow",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "assignOilPressure",
    syncOperationLanguage: "typescript",
    handler: assignOilPressure,
  },
  {
    fsmName: "vitalsWorkflow",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "assignCoolantLevel",
    syncOperationLanguage: "typescript",
    handler: assignCoolantLevel,
  },
  {
    fsmName: "vitalsWorkflow",
    fsmVersion: "v02",
    syncOperationType: "action",
    syncOperationName: "assignBattery",
    syncOperationLanguage: "typescript",
    handler: assignBattery,
  },
];
