import { build, emptyDir } from "@deno/dnt";

await emptyDir("./dist");

const packageVersion = Deno.args[0]?.replace(/^v/, "") ?? "0.0.0";

// Both CLIs' --version flag needs this build's actual version string, which
// deno.json only has for the Deno-native path — generate the npm-build
// variant of src/cli/version.ts fresh on every build:npm run rather than
// hand-maintaining it (see .gitignore: this file isn't committed, since the
// version differs per release). Same pattern as fsm-compiler-ts's
// build-npm.ts (#258).
await Deno.writeTextFile(
  "./src/cli/version.node.ts",
  `// Auto-generated by scripts/build-npm.ts for this build only — not committed, do not edit.\nexport const PACKAGE_VERSION: string = ${
    JSON.stringify(packageVersion)
  };\n`,
);

// @pgfsm/db is published to npm independently (unlike @pgfsm/logging, which
// isn't in .github/workflows/npm-publish.yml's matrix and stays vendored) —
// map it to the real npm dependency instead of letting dnt inline its
// source, so a fix published there reaches this package via semver instead
// of requiring a republish here too. Version is read from its own deno.json
// rather than hardcoded, so it can't silently drift from whatever this
// build actually resolved locally. Same pattern as fsm-sync-worker-ts's
// build-npm.ts mapping @pgfsm/compiler (#283).
const dbDenoJson = JSON.parse(
  await Deno.readTextFile("../fsm-core-db-ts/deno.json"),
);
const dbVersionRange = `^${dbDenoJson.version}`;

await build({
  entryPoints: [
    "./src/index.ts",
    {
      kind: "bin",
      name: "async-operation-worker-gateway",
      path: "./src/cli/async-operation-worker-gateway.ts",
    },
    {
      kind: "bin",
      name: "async-operation-worker-gateway-ctl",
      path: "./src/cli/async-operation-worker-gateway-ctl.ts",
    },
  ],
  outDir: "./dist",
  shims: {
    deno: true,
  },
  // Both CLIs' help text shows how to invoke them, and --version prints
  // this build's version — both differ between this Deno source and the
  // published npm CLI. Runtime detection doesn't work here (see
  // fsm-compiler-ts's build-npm.ts, #254/#258, for why) — swap the whole
  // module instead, one invocation-text pair per bin since each bin's
  // correct npm invocation differs by name.
  mappings: {
    "./src/cli/gateway-invocation.ts": "./src/cli/gateway-invocation.node.ts",
    "./src/cli/gateway-ctl-invocation.ts":
      "./src/cli/gateway-ctl-invocation.node.ts",
    "./src/cli/version.ts": "./src/cli/version.node.ts",
    "@pgfsm/db": { name: "@pgfsm/db", version: dbVersionRange },
  },
  package: {
    name: "@pgfsm/async-worker",
    version: packageVersion,
    description:
      "Activity Gateway (async-operation-worker-gateway/-ctl) for async-operation-type FSM operations across polyglot actors",
    license: "Apache-2.0",
    // pg ships no types of its own; dnt only auto-installs packages that
    // are themselves import specifiers, so without this the type-check
    // pass can't resolve `import ... from "pg"` (deno.json's own
    // "@types/pg" import mapping isn't picked up the same way here).
    devDependencies: {
      "@types/pg": "^8.18.0",
    },
  },
  compilerOptions: {
    lib: ["ES2022", "DOM"],
    target: "ES2022",
  },
  postBuild() {
    if (Deno.args.includes("--copy-readme")) {
      Deno.copyFileSync("README.md", "dist/README.md");
    }
  },
});
