// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { fetchTasks } from "./fetchTasks/fetchTasks.ts";
import { updateTask } from "./updateTask/updateTask.ts";

export type ActorRegistration = {
  parentFsmName: string;
  parentFsmVersion: string;
  asyncOperationType: string;
  asyncOperationName: string;
  asyncOperationVersion: string;
  asyncOperationLanguage: string;
  handler: (input: unknown) => unknown;
};

export const ACTOR_REGISTRATIONS: ActorRegistration[] = [
  {
    parentFsmName: "taskMachineConfig",
    parentFsmVersion: "v02",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "fetchTasks",
    asyncOperationVersion: "v02",
    asyncOperationLanguage: "typescript",
    handler: fetchTasks,
  },
  {
    parentFsmName: "taskMachineConfig",
    parentFsmVersion: "v02",
    asyncOperationType: "internalAsyncOperation",
    asyncOperationName: "updateTask",
    asyncOperationVersion: "v02",
    asyncOperationLanguage: "typescript",
    handler: updateTask,
  },
];
