# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
from .actors.checkBureau.checkBureau import checkBureau, MAX_CONCURRENCY as _max_concurrency_checkBureau

ACTOR_REGISTRATIONS = [
    {
        "parent_fsm_name": "creditCheck",
        "parent_fsm_version": "v01",
        "async_operation_type": "internalAsyncOperation",
        "async_operation_name": "checkBureau",
        "async_operation_version": "v01",
        "async_operation_language": "python",
        "max_concurrency": _max_concurrency_checkBureau,
        "handler": checkBureau,
    },
]
