// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { SYNC_OPERATION_REGISTRATIONS } from "./aggregate-generated-sync-operation-registry.ts";
import { runFsmlet } from "@pgfsm/sync-worker";

await runFsmlet(
  { connectionString: Deno.env.get("DATABASE_URL") ?? "" },
  SYNC_OPERATION_REGISTRATIONS,
);
