// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { byeFromPgfsm as byeFromPgfsm_v01 } from "./actors/byeFromPgfsm/byeFromPgfsm.ts";
import { helloFromPgfsm as helloFromPgfsm_v01 } from "./actors/helloFromPgfsm/helloFromPgfsm.ts";

export type ActorRegistration = {
  parentFsmName: string;
  parentFsmVersion: string;
  asyncOperationType: string;
  asyncOperationName: string;
  asyncOperationVersion: string;
  asyncOperationLanguage: string;
  handler: (input: unknown) => unknown;
};

export const ACTOR_REGISTRATIONS: ActorRegistration[] = [
  {
    parentFsmName: "sharedAsyncOperation",
    parentFsmVersion: "v01",
    asyncOperationType: "sharedAsyncOperation",
    asyncOperationName: "byeFromPgfsm",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    handler: byeFromPgfsm_v01,
  },
  {
    parentFsmName: "sharedAsyncOperation",
    parentFsmVersion: "v01",
    asyncOperationType: "sharedAsyncOperation",
    asyncOperationName: "helloFromPgfsm",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    handler: helloFromPgfsm_v01,
  },
];
