// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
package generatedregistry

import (
	byeFromPgfsm_v01 "apps/shared-async-op/v01/go/actors/byefrompgfsm"
	helloFromPgfsm_v01 "apps/shared-async-op/v01/go/actors/hellofrompgfsm"
)

type ActorRegistration struct {
	ParentFsmName          string
	ParentFsmVersion       string
	AsyncOperationType     string
	AsyncOperationName     string
	AsyncOperationVersion  string
	AsyncOperationLanguage string
	Handler                func(input any) (any, error)
}

func ActorRegistrations() []ActorRegistration {
	return []ActorRegistration{
		{
			ParentFsmName:          "sharedAsyncOperation",
			ParentFsmVersion:       "v01",
			AsyncOperationType:     "sharedAsyncOperation",
			AsyncOperationName:     "byeFromPgfsm",
			AsyncOperationVersion:  "v01",
			AsyncOperationLanguage: "go",
			Handler:                byeFromPgfsm_v01.ByeFromPgfsm,
		},
		{
			ParentFsmName:          "sharedAsyncOperation",
			ParentFsmVersion:       "v01",
			AsyncOperationType:     "sharedAsyncOperation",
			AsyncOperationName:     "helloFromPgfsm",
			AsyncOperationVersion:  "v01",
			AsyncOperationLanguage: "go",
			Handler:                helloFromPgfsm_v01.HelloFromPgfsm,
		},
	}
}
