// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { ACTOR_REGISTRATIONS as creditcheck_v01 } from "./creditCheck/v01/generated-registry.ts";
import { ACTOR_REGISTRATIONS as creditcheck_v02 } from "./creditCheck/v02/generated-registry.ts";
import { ACTOR_REGISTRATIONS as vitalsworkflow_v01 } from "./vitalsWorkflow/v01/generated-registry.ts";
import { ACTOR_REGISTRATIONS as vitalsworkflow_v02 } from "./vitalsWorkflow/v02/generated-registry.ts";
import { ACTOR_REGISTRATIONS as taskmachineconfig_v01 } from "./taskMachineConfig/v01/generated-registry.ts";
import { ACTOR_REGISTRATIONS as taskmachineconfig_v02 } from "./taskMachineConfig/v02/generated-registry.ts";

export const ACTOR_REGISTRATIONS = [
  ...creditcheck_v01,
  ...creditcheck_v02,
  ...vitalsworkflow_v01,
  ...vitalsworkflow_v02,
  ...taskmachineconfig_v01,
  ...taskmachineconfig_v02,
];
